### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by bartlebi** [AlexxIT/YandexStation#113]
После добавления диалогов в HA, при отправке любого сообщения в консоли ошибка

Traceback (most recent call last):                                                                                                      
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 41, in _process                                     
    await process_platform(hass, component_name, platform)                                                                              
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 44, in _async_process_intent                          
    await platform.async_setup_intents(hass)                                                                                            
  File "/config/custom_components/yandex_station/intent.py", line 20, in async_setup_intents                                            
    if 'host' in device or device['platform'].startswith('yandex'):                                                                     
TypeError: string indices must be integers

**Comment by AlexxIT** [comment]
А точно последняя версия компонента?

**Comment by bartlebi** [comment]
Да, 3.0.1.

**Comment by AlexxIT** [comment]
Дубликат #97 
Будет поправлено в рамках той задачи
