### ISSUE TITLE
Waiting on integrations to complete setup: yandex_station

### ISSUE THREAD

**Issue by Elnio13** [AlexxIT/YandexStation#116]
Интеграцию установил, в конфигурации логин, пароль. В логах HA:
Logger: homeassistant.bootstrap
Source: bootstrap.py:392
First occurred: 4:02:16 PM (278 occurrences)
Last logged: 8:39:20 PM

Waiting on integrations to complete setup: yandex_station

больше ничего не происходит.
Файла .yandex_station,json в корне нет

**Comment by belemle** [comment]
Подтверждаю. Интеграция не запускается из-за ошибки: 
```
Logger: homeassistant
Source: custom_components/yandex_station/core/yandex_session.py:111
First occurred: 20:10:09 (1 occurrences)
Last logged: 20:10:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/yandex_station/config_flow.py", line 44, in async_step_import
    return await self.async_step_auth(data)
  File "/config/custom_components/yandex_station/config_flow.py", line 59, in async_step_auth
    resp = await self.yandex.login_username(user_input['username'],
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 111, in login_username
    r = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobileproxy.passport.yandex.net:443 ssl:default [Network unreachable]
```  
Ошибка появляется через какое-то время после запуска HA. С сетью все в порядке. До появления ошибки HACS висит в ожидании запуска интеграции.

**Comment by AlexxIT** [comment]
@Elnio13 последняя версия настраивается через GUI. Возможно у вас там капчу спрашивают

**Comment by AlexxIT** [comment]
@belemle у вас обычные проблемы с интернетом. ХА не может достучаться до сервера Яндекса

**Comment by Elnio13** [comment]
> @Elnio13 последняя версия настраивается через GUI. Возможно у вас там капчу спрашивают
Вообще не понимаю через какой GUI настраивать. Мой интерфейс в YAML mode, автоматически карточка не появляется. Не появляется ни объект ни девайс, добавить в интерфейс нечего.

**Comment by Elnio13** [comment]
Заработало. Я до конца так и не понял что произошло.

Пожалуйста, напишите нормальную инструкцию по установке!!! Три дня выковыривал по крупицам как установить этот прекраснейший и крайне полезный компонент!!!
