### ISSUE TITLE
Проблемы после обновления 3.0.4

### ISSUE THREAD

**Issue by DeniMGL** [AlexxIT/YandexStation#124]
После обновления пропал вообще media_player.yandex_intents
Вот что пишет в логах:
1)
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/yandex_station/media_player.py", line 678, in device_info
    'identifiers': {(DOMAIN, self._unique_id)},
TypeError: unhashable type: 'list'
```
2)
```
Error adding entities for domain media_player with platform yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/yandex_station/media_player.py", line 678, in device_info
    'identifiers': {(DOMAIN, self._unique_id)},
TypeError: unhashable type: 'list'
```

**Comment by EropForWork** [comment]
Ага, не создаёт теперь intents.
```
Error adding entities for domain media_player with platform yandex_station
Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/yandex_station/media_player.py", line 678, in device_info
    'identifiers': {(DOMAIN, self._unique_id)},
TypeError: unhashable type: 'list'
```

**Comment by ARNik** [comment]
Точно такая же проблема.

**Comment by snkku** [comment]
а я уже все попереустанавливал, всё перепроверил... а оно вона что )))

**Comment by ARNik** [comment]
2021-02-24 22:35:42 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_session] Login in Yandex with token
2021-02-24 22:35:43 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_quasar] Получение списка устройств.
2021-02-24 22:35:44 ERROR (MainThread) [homeassistant.components.media_player] Error adding entities for domain media_player with platform yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/yandex_station/media_player.py", line 678, in device_info
    'identifiers': {(DOMAIN, self._unique_id)},
TypeError: unhashable type: 'list'
2021-02-24 22:35:44 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/yandex_station/media_player.py", line 678, in device_info
    'identifiers': {(DOMAIN, self._unique_id)},
TypeError: unhashable type: 'list'

**Comment by snkku** [comment]
я для себя поправил, всё работает ) автор, когда правки внесешь?

**Comment by firemdkfighter** [comment]
Ждём хотфикс)

**Comment by ARNik** [comment]
После коммита Fix YandexIntents #124
ошибки в логах пропали, но плеер так и не подключается к яндексу.

**Comment by EropForWork** [comment]
1. Переустановил модуль Яндекс Станции на версию Master
2. Появился плеер, назsвается Яндекс сценарии
3. Перезагрузил HA
4. Обновил устройства в приложении Яндекса
5. Добавился Медиа плеер "Яндекс сценарии". Никуда его не двигал, не переименовывал, как intents раньше.
6. Перезагрузил HA
7. В приложении Яндекса не добавились сценарии.

**Comment by snkku** [comment]
custom_components/yandex_station/core/yandex_quasar.py
строка 51
            if device['name'] == "Yandex Intents":
на
            if device['name'] == "Яндекс Сценарии":

**Comment by AlexxIT** [comment]
Печаль. Я сильно переделал логику интентов. Для релиза ещё не готово. И вот куски случайно попали в эту версию

**Comment by AlexxIT** [comment]
Попробуйте последнее исправление

**Comment by ARNik** [comment]
> Попробуйте последнее исправление

Заработало! 
Появился плеер Yandex Intents, сценарии добавились.

**Comment by userX32** [comment]
Да, с последним обновлением заработало.

**Comment by snkku** [comment]
> Попробуйте последнее исправление

обновил, удалил "яндекс сценарии" из яндекса, теперь там Yandex Intents не создается и сценарии не обновляются...

**Comment by shostko** [comment]
Только сегодня решил попробовать intents. Долго пытался понять, почему же не появляется `media_player.yandex_intents` даже на последней версии.
Оказалось, что теперь надо в конфиге указывать собственно этот блок `intents:`, без этого устройство не создавалось.
А так-то всё работает! :+1:

**Comment by AlexxIT** [comment]
Логично, зачем создавать этот медиаплеер для пользователей, кому он не нужен. Будут только лишние вопросы

**Comment by shostko** [comment]
> Логично, зачем создавать этот медиаплеер для пользователей, кому он не нужен. Будут только лишние вопросы

Согласен, но на предыдущих версиях компонента мелиаплеер у меня болтался, хотя блока `intents:` в конфигурации еще не было. 
Поэтому написал, может кому тоже будет полезно.

**Comment by sushami** [comment]
Настроил все с нуля, плеер есть, сценарии создаются, но события yandex_intent не доходят до HA и автоматизация не запускается.

**Comment by firemdkfighter** [comment]
> Настроил все с нуля, плеер есть, сценарии создаются, но события yandex_intent не доходят до HA и автоматизация не запускается. Проверял через Панель разработчика, если там же создавать события, то оно естественно прилетает, а с колонки нет.

Посмотри логи.

**Comment by sushami** [comment]
Error processing platform yandex_station.intent

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 41, in _process
    await process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 42, in _async_process_intent
    await platform.async_setup_intents(hass)
  File "/config/custom_components/yandex_station/intent.py", line 20, in async_setup_intents
    platform = device['quasar_info']['platform']
KeyError: 'quasar_info'

**Comment by AlexxIT** [comment]
Не актуально
