### ISSUE TITLE
Ошибка при попытке вызвать TTS

### ISSUE THREAD

**Issue by ZeBriD** [AlexxIT/YandexStation#138]
При попытке отправить текст на произнесение фразы выдаёт ошибку 400.
Не работает ни на мини, ни на макс станциях.

Версия плагина 3.1.1

Вызов TTS производится следующим методом:
```
      - service: media_player.play_media
        entity_id: media_player.yandex_station_some
        data:
          media_content_type: text
          media_content_id: Тест
```

В логах ошибка следующего вида:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/yandex_station/core/yandex_session.py:295
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:10:40 (3 occurrences)
Last logged: 22:11:38

[2891617592] https://iot.quasar.yandex.ru/m/user/scenarios/9155d8d9-0000-0000-0000-a157a06433aa return 400 status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/yandex_station/__init__.py", line 178, in yandex_station_say
    await hass.services.async_call(DOMAIN_MP, SERVICE_PLAY_MEDIA, data,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/config/custom_components/yandex_station/media_player.py", line 596, in async_play_media
    await self.quasar.send(self.device, media_id, is_tts=True)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 205, in send
    r = await self.session.put(f"{URL_USER}/scenarios/{sid}", json=payload)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 258, in put
    return await self._request('put', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 295, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios/9155d8d9-0000-0000-0000-a157a06433aa return 400 status
```

**Comment by netdoggy** [comment]
Я сегодня впервые попытался подвязаться и получил тоже самое в логе. Похоже поменяли адреса или api

**Comment by dsyntech** [comment]
+1 Тоже самое у меня

**Comment by ARNik** [comment]
+1 Сегодня перестало работать.

**Comment by direktorov** [comment]
тоже перестало работать , переустановка тоже не помогла....

**Comment by Valerich1971** [comment]
+1 тоже самое

**Comment by andyidnn** [comment]
17 марта днем еще работало, а вечером перестало, такая же ошибка. Пробовал переустановить на разные версии - ничего не помогает, ошибка после перезагрузки ХА такая:

```
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_session.py:295
Integration: Медиаплеер (documentation, issues)
First occurred: 0:01:30 (1 occurrences)
Last logged: 0:01:30

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 72, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 88, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 136, in add_scenario
    r = await self.session.post(f"{URL_USER}/scenarios", json=payload)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 255, in post
    return await self._request('post', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 295, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios return 400 status
```

**Comment by anatoly-kryzhanovsky** [comment]
same situation.
after installing stable version i receive followiing error:


```
2021-03-18 07:15:19 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 72, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 88, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 136, in add_scenario
    r = await self.session.post(f"{URL_USER}/scenarios", json=payload)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 255, in post
    return await self._request('post', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 295, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios return 400 status

```

**Comment by Zwhouse2021** [comment]
Да. Я уж думал пробовать все заново вместе с ассистантом переустанавливать, только уже на малину, а не на ВМ. Управление алисой осуществляется все так же хорошо, но текст она не произносит. Ждем ответа от автора. Я пока что из аналогичных решений видел только платное с Яндекс.Облако

**Comment by anatoly-kryzhanovsky** [comment]
in my case (first time setup and configuration) i even can't setup Alisa - device does not appear and no other log

**Comment by anatoly-kryzhanovsky** [comment]
still getting same error (after update to latest version)
```
2021-03-18 10:01:22 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 72, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 88, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 136, in add_scenario
    r = await self.session.post(f"{URL_USER}/scenarios", json=payload)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 255, in post
    return await self._request('post', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 295, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios return 400 status
```

**Comment by anatoly-kryzhanovsky** [comment]
last update solve issue, thanks

**Comment by ARNik** [comment]
Спасибо! Заработало!

**Comment by andyidnn** [comment]
Спасибо, работает))

**Comment by Valerich1971** [comment]
у меня не заработало , переустанавливать пробовал  ре работает даже с карточки ловлэйс
Exception: https://iot.quasar.yandex.ru/m/user/scenarios/63ba7aa5-3d98-4fc3-ba15-68bd7e1f804c return 400 status

**Comment by Valerich1971** [comment]
извините !!! ступил! не обновил интеграцию!!! все работает спасибо!!!

**Comment by darkfessing** [comment]
Тоже была такая проблема на днях, но обновление все исправило. Спасибо!
