### ISSUE TITLE
Перестал работать второй способ вызова TTS

### ISSUE THREAD

**Issue by sushami** [AlexxIT/YandexStation#139]
Примерно неделю назад отвалился TTS, ответ ошибка 400 от сервера Яндекса, видео и музыка работают. Help!
Выяснилось, что не работает именно второй метод вызова TTS: media_content_type: text , а только через него происходит   
корректная озвучка с параметрами TTS яндекса.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/yandex_station/core/yandex_session.py:295
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:59:48 (4 occurrences)
Last logged: 14:15:11
[140452161677728] https://iot.quasar.yandex.ru/m/user/scenarios/9fa6e463-ba9d-4302-97be-c5d8090eb963 return 400 status

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1026, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 242, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 457, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/config/custom_components/yandex_station/media_player.py", line 596, in async_play_media
    await self.quasar.send(self.device, media_id, is_tts=True)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 205, in send
    r = await self.session.put(f"{URL_USER}/scenarios/{sid}", json=payload)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 258, in put
    return await self._request('put', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 295, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios/9fa6e463-ba9d-4302-97be-c5d8090eb963 return 400 status

**Comment by AlexxIT** [comment]
Это дубль #138 и он уже исправлен. Только ту ошибку создали два дня назад. Точно целую неделю не работало?

**Comment by sushami** [comment]
Спасибо, не точно, может и правда два дня

**Comment by eXzertus** [comment]
Не работает TTS ошибка 400 
Все тоже самое, есть решение!????
Легло все, все управление через голосовое и с озвучкой, теперь как кот в мешке!

**Comment by dserv333** [comment]
Сегодня тоже стала выдаваться ошибка: "Не удалось выполнить действие script/unknown_4. https://iot.quasar.yandex.ru/m/user/scenarios/#####-###-####-######### return 400 status"

data:
  media_content_id: Текст для произнесения колонкой
  media_content_type: text
target:
  entity_id: media_player.yandex_station_#########
action: media_player.play_media
