### ISSUE TITLE
Ошибка при добавлении нового устройства

### ISSUE THREAD

**Issue by dmamontov** [AlexxIT/YandexStation#141]
При нажатии настроить
<img src="https://user-images.githubusercontent.com/5955726/112295333-dc17bb00-8ca4-11eb-8acc-9bb39febe048.png" data-canonical-src="https://user-images.githubusercontent.com/5955726/112295333-dc17bb00-8ca4-11eb-8acc-9bb39febe048.png" width="300" />

Получаем 
<img src="https://user-images.githubusercontent.com/5955726/112295419-f0f44e80-8ca4-11eb-8bd6-0a57bafe3c93.png" data-canonical-src="https://user-images.githubusercontent.com/5955726/112295419-f0f44e80-8ca4-11eb-8bd6-0a57bafe3c93.png" width="400" />

Интеграция с 2-мя станциями добавлена и работает. на 3-ей возникает вот такая проблема. Приобрел не давно.

Лог:
```
ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 141, in get
    return await super().get(request, flow_id)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 92, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/opt/homeassistant/config/custom_components/yandex_station/config_flow.py", line 79, in async_step_auth
    resp = await self.yandex.login_username(user_input['username'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AlexxIT** [comment]
Точно последняя версия компонента?

**Comment by dmamontov** [comment]
> Точно последняя версия компонента?

обновил до 3.2.0, все так же. Сейчас заметил что не новую станцию он пытается а старую которая была.

Как это вышло. Яндекс забанил акк просил сменить пасс. везде поменял в интеграции тоже. но теперь постоянно находит уже подключенное устройство. Пробовал уже и перезагружать и тп

**Comment by dmamontov** [comment]
Разобрался в чем проблема. пароль поменял только в GUI, в yaml не менял. Поменял в yaml и все стало нормально

**Comment by AlexxIT** [comment]
Логин/пароль из yaml можно удалить
