### ISSUE TITLE
после обновления просит заново установить и настроить интеграцию

### ISSUE THREAD

**Issue by StetskoSergey** [AlexxIT/YandexStation#142]
но при настройке интеграции авторизация не работает вообще никак, ни через пароль, ни через coocies

1. лог при авторизации cookies и через пароль
2021-03-31 07:17:11 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
Traceback (most recent call last):
  File "C:\ha\python-3.8.7\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ha\python-3.8.7\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2. при попытке настроить текущую интеграцию, которая обнаруживается автоматически
2021-03-31 07:16:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "C:\ha\python-3.8.7\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\http\security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\http\request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\http\ban.py", line 72, in ban_middleware
    return await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\http\auth.py", line 129, in auth_middleware
    return await handler(request)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\http\view.py", line 129, in handle
    result = await result
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\components\config\config_entries.py", line 141, in get
    return await super().get(request, flow_id)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\helpers\data_entry_flow.py", line 92, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "C:\ha\python-3.8.7\lib\site-packages\homeassistant\data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "C:\ha\config\custom_components\yandex_station\config_flow.py", line 100, in async_step_external
    return await self.async_step_auth(user_input)
  File "C:\ha\config\custom_components\yandex_station\config_flow.py", line 79, in async_step_auth
    resp = await self.yandex.login_username(user_input['username'],
TypeError: 'NoneType' object is not subscriptable

**Comment by AlexxIT** [comment]
Какой версии интеграция? Версия есть в файле `manifest.json`

**Comment by StetskoSergey** [comment]
{
  "domain": "yandex_station",
  "name": "Yandex.Station",
  "config_flow": true,
  "documentation": "https://github.com/AlexxIT/YandexStation",
  "dependencies": [
    "tts",
    "zeroconf"
  ],
  "codeowners": [
    "@AlexxIT"
  ],
  "requirements": [],
  "version": "3.3.0"
}

**Comment by AlexxIT** [comment]
Вероятно логин есть в YAML. Он совпадает с логином в GUI?

**Comment by StetskoSergey** [comment]
судя по всему раз все работает, значит реальной надобности что-то чинить нет, извините.
просто история была такая 👍 
1) после последнего обновления она написала, что нужно переустановить интеграцию,
2) я удалил текущую интеграцию в GUI
3) и больше ничего установить она в GUI не дает из-за ошибок выше
4) а в реальности все работает, так как все настройки остались в YAML

**Comment by AlexxIT** [comment]
Не актуально
