### ISSUE TITLE
Cookie auth doesn't work

### ISSUE THREAD

**Issue by nazmang** [AlexxIT/YandexStation#151]
hi,

I can't setup integration due to neither cookie nor logon/password authentication don't work
![image](https://user-images.githubusercontent.com/26415965/116134846-0b24b080-a6d9-11eb-83a5-46c6608c6938.png)
Seeing errors below
```
2021-04-26 21:44:44 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/yandex_station/config_flow.py", line 84, in async_step_cookies
    resp = await self.yandex.login_cookies(user_input['cookies'])
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 173, in login_cookies
    x_token = resp['access_token']
`
`2021-04-26 21:37:53 WARNING (SyncWorker_4) [homeassistant.components.zeroconf.usage] Detected code that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass); Please report this issue
Stack (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 24, in new_zeroconf_new
    _report(
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 47, in _report
    _LOGGER.warning(
Stack (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 24, in new_zeroconf_new
    _report(
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 47, in _report
    _LOGGER.warning(
```

**Comment by AlexxIT** [comment]
Попробуйте ещё раз авторизоваться через cookie. Вы случайно не в Украине?

**Comment by nazmang** [comment]
Случайно в Украине. Yandex Plus настроен через VPN, Алиса работает по IPv6.

**Comment by AlexxIT** [comment]
До какого именно обновления?

**Comment by nazmang** [comment]
После обновления homeassistant до 2021.4.6

**Comment by AlexxIT** [comment]
Проверьте, что вы копируете куки с правильного сайта, строго по инструкции

**Comment by maxp0d** [comment]
Тоже никак не получалось, но делал через Оперу. Стоило попробовать через Хром - всё нормально сработало.

**Comment by nazmang** [comment]
У меня с нормальными настройками VPN даже получилось через Opera при помощи куки. Я думаю данный кейс можно закрывать. Всем спасибо!
