### ISSUE TITLE
Яндекс.Станция слетает после перезапуска сервера Home Assistant

### ISSUE THREAD

**Issue by GiiRiiOZ** [AlexxIT/YandexStation#153]
Добрый день!
Компонент перестает работать через раз после того как перезапускаю сервер. Удаляю и снова устанавливаю компонент и снова все работает
Когда не запускается выдает ошибку:
![image](https://user-images.githubusercontent.com/67837968/116979410-a5828680-accd-11eb-81fb-abb5476ae374.png)

**Comment by AlexxIT** [comment]
Украина?

**Comment by GiiRiiOZ** [comment]
Нет, Россия

**Comment by AlexxIT** [comment]
Странно, обычное подключение к серверам Яндекса. Посмотрим, если проблема массовая

**Comment by ShammanIT** [comment]
Тоже ошибка вылезла

**Comment by kvashninsa** [comment]
Error setting up entry for yandex_station
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/yandex_station/__init__.py", line 79, in async_setup_entry
    if not await yandex.refresh_cookies():
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 226, in refresh_cookies
    ok = await self.login_token(self.x_token)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 210, in login_token
    r = await self.session.get(f"{host}/auth/session/", params=payload,
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host passport.yandex.ru:443 ssl:default [Try again]

**Comment by AlexxIT** [comment]
@kvashninsa страна какая?

**Comment by kvashninsa** [comment]
@AlexxIT Россия

**Comment by Drun555** [comment]
Сегодня внезапно вылезло. г. Саратов, дом.ру. 
Понимаю, что проблема не в интеграции - пока пересадил малинку на нидерландский ВПН, там все работает. Пишу, чтобы держать в курсе.

**Comment by AlexxIT** [comment]
В релизе 3.6 добавлен отложенный старт интеграции при проблемах с интернетом
