### ISSUE TITLE
Вдруг перестал работать локальный протокол

### ISSUE THREAD

**Issue by lexxstorm** [AlexxIT/YandexStation#161]
Logger: homeassistant
Source: aiohttp/connector.py:971
First occurred: May 26, 2021, 6:26:40 PM (3 occurrences)
Last logged: May 26, 2021, 6:26:55 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/config/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/config/aiohttp/connector.py", line 815, in _resolve_host
    await event.wait()
  File "/config/aiohttp/locks.py", line 37, in wait
    raise self._exc
  File "/config/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/config/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 82, in _connect
    self.device_token = await self.get_device_token()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 53, in get_device_token
    r = await self.session.get(
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 251, in get
    return await self._request_glagol(url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 305, in _request_glagol
    r = await self.session.get(url, headers=headers, **kwargs)
  File "/config/aiohttp/client.py", line 483, in _request
    conn = await self._connector.connect(
  File "/config/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/config/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/config/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host quasar.yandex.net:443 ssl:default [Try again]

**Comment by AlexxIT** [comment]
`Cannot connect to host quasar.yandex.net:443` сервера Яндекса были недоступны

**Comment by lexxstorm** [comment]
Как сейчас инициировать подключение по локальному протоколу?
