### ISSUE TITLE
Ошибка в ha 2021.5.5

### ISSUE THREAD

**Issue by runnerfanspb** [AlexxIT/YandexStation#163]
Эта ошибка возникла в кастомной интеграции.

```
Logger: homeassistant
Source: custom_components/yandex_station/core/yandex_glagol.py:137
Integration: Yandex.Station (documentation)
First occurred: 7:42:23 (2 occurrences)
Last logged: 7:42:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 125, in _connect
    await self.update_handler(data)
  File "/config/custom_components/yandex_station/media_player.py", line 457, in internal_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity None: idle>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 137, in _connect
    assert e.args[0] == "Session is closed", e.args
AssertionError: ('Attribute hass is None for <Entity None: idle>',)
```

как данную проблему можно побороть?

**Comment by AlexxIT** [comment]
Поправлено в последней master версии
