### ISSUE TITLE
Yandex station mini no entity after setup

### ISSUE THREAD

**Issue by minskmail** [AlexxIT/YandexStation#200]
Yandex station mini doesn't present as entity after integration setup and configuration.

Error from logs

Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:44
Integration: Media Player (documentation, issues)
First occurred: 21:41:30 (1 occurrences)
Last logged: 21:41:30

```
Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 80, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 90, in load_speakers
    scenarios = await self.load_scenarios()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 119, in load_scenarios
    return {
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 120, in <dictcomp>
    decode(d['name']): d
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 44, in decode
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 44, in <listcomp>
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
ValueError: substring not found
```

![image](https://user-images.githubusercontent.com/25284132/142918585-21a06742-86fd-4ccc-9a35-b49f91509de3.png)

**Comment by AlexxIT** [comment]
Go to scenarios list in Yandex mobile app and remove all scenarios that starts with XA...

**Comment by minskmail** [comment]
> Go to scenarios list in Yandex mobile app and remove all scenarios that starts with XA...

Yuup. Problem resolved. Thanks.
But I'm little bit confused... How its possible from that logs to know that I have scenarios that starts with XA? 
Its because service scenario starts from the same letters so thats lead to some conflict or ....? ))

**Comment by AlexxIT** [comment]
Yes. Same letters
