### ISSUE TITLE
3.6 - release candidate - сломалось локальное управление YandexModule v1

### ISSUE THREAD

**Issue by anklimov** [AlexxIT/YandexStation#206]
После установки обновления, HA перестает отслеживать что проигрывается на Модуле v1
Также, не работает управление громкостью Модуля (только пауза и стоп работают)

UPDATE
Яндекс модуль отваливается если попытаться сделать трансляцию (google mini, chrome). 

В логах : 2021-12-04 15:45:44 ERROR (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Модуль 1 | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 127, in _connect
    self.update_handler(data)
  File "/config/custom_components/yandex_station/media_player.py", line 292, in async_set_state
    if self.sync_id != pstate["id"]:
KeyError: 'id'
2021-12-04 15:46:14 ERROR (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Модуль 1 | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 127, in _connect
    self.update_handler(data)
  File "/config/custom_components/yandex_station/media_player.py", line 292, in async_set_state
    if self.sync_id != pstate["id"]:
KeyError: 'id'

после возвращения режима звука в "выполни команду" локальный режим (с контролем того что играет, громкости) со временем все же восстанавливается. Видимо, один раз почему-то не восстановилось... Судя по всему, у хромкаста, гугловой колонки и пр не хватает какого-то id

**Возвращение проигрывания на Модуль:**

2021-12-04 16:09:03 WARNING (SyncWorker_7) [pychromecast.controllers] PAUSE command requested but no session is active.

после этого, спустя какое-то время, локальное управление Модулем 1 восстанавливается (за редким исключением)

**Comment by AlexxIT** [comment]
Поправлено в последней master-версии. Но первый модуль не поддерживает трансляцию
