### ISSUE TITLE
Проблемы с user/pass в YAML

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/YandexStation#214]
```yaml
Logger: homeassistant
Source: custom_components/yandex_station/config_flow.py:186
Integration: yandex_station (documentation, issues)
First occurred: 14:38:36 (1 occurrences)
Last logged: 14:38:36
Error doing job: Task exception was never retrievedTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init flow, result = await task File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init result = await self._async_handle_step(flow, flow.init_step, data, init_done) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step result: FlowResult = await getattr(flow, method)(user_input) File "/config/custom_components/yandex_station/config_flow.py", line 42, in async_step_import return await self.async_step_auth(data) File "/config/custom_components/yandex_station/config_flow.py", line 102, in async_step_auth return await self._check_yandex_response(resp) File "/config/custom_components/yandex_station
```

**Comment by AlexeyZhukoff** [comment]
У меня сейчас не загружается дополнение, я так понимаю это этот баг?

**Comment by AlexxIT** [comment]
Если у вас остались логин/пароль в YAML, то возможно это проблема. Не нужны они там давно
