### ISSUE TITLE
Не работает ТТS в плеере станция Яндекс лайт

### ISSUE THREAD

**Issue by Vorchikhin** [AlexxIT/YandexStation#222]
Не работает в плеере выполнить команды и произнести текст
Работает только громкость и плай.
HA 2021.12.4
Yandex.Station 3.7.0

Но в скрипте произносит текст!
```
  - service: media_player.play_media
    data:
      media_content_type: text
      media_content_id: Вода на полу санузел
    target:
      entity_id: media_player.yandex_station_lb00000000000003040900004d72dc44
```

```
Logger: custom_components.yandex_station.core.utils
Source: custom_components/yandex_station/core/utils.py:233
Integration: Yandex.Station (documentation, issues)
First occurred: 22 декабря 2021 г., 23:57:51 (17 occurrences)
Last logged: 00:18:30

Ошибка получения сообщения TTS
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/utils.py", line 233, in get_tts_message
    r = await session.get(url, ssl=False)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by AlexxIT** [comment]
У вас есть несколько TTS в конфиге (описано в документации) и криво настроен доступ в ХА. Можно починить любую из этих проблем

**Comment by Vorchikhin** [comment]
Спасибо за ответ. снести и заново настроить?

**Comment by AlexxIT** [comment]
Вы про весь ХА? Потому что проблемы именно в его настройке

**Comment by AlexxIT** [comment]
Начиная с Hass v2022.3 поменяли вызов TTS из плеера и такой проблемы быть не должно
