### ISSUE TITLE
Ошибка про увлажнитель. Версия 3.7.0

### ISSUE THREAD

**Issue by Kuzav** [AlexxIT/YandexStation#223]
Добрый день.
После обновления с версии 3.6.х (точно не помню версию) до v3.7.0
в логах всегда две ошибки.
Одна точно про увлажнитель.
Увлажнитель я не использую ни подключенным к Алисе ни в Home assistant вообще.
Версия Home Assistant 2021.6.6

Эта ошибка возникла в кастомной интеграции.

```
Logger: homeassistant.config_entries
Source: custom_components/yandex_station/humidifier.py:125
Integration: Yandex.Station (documentation, issues)
First occurred: 23:16:53 (1 occurrences)
Last logged: 23:16:53

Error setting up entry kuzav1 for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 94, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 328, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/yandex_station/humidifier.py", line 52, in <module>
    class YandexHumidifier(HumidifierEntity):
  File "/config/custom_components/yandex_station/humidifier.py", line 125, in YandexHumidifier
    def extra_state_attributes(self) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable

Logger: homeassistant.setup
Source: setup.py:310
First occurred: 23:16:53 (1 occurrences)
Last logged: 23:16:53

Unable to prepare setup for platform yandex_station.sensor: Platform not found (cannot import name 'SensorEntityDescription' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
```

Ранее таких ошибок не было.

**Comment by AlexxIT** [comment]
Ошибка повторяется на 3.8.0?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
