### ISSUE TITLE
Интеграция не добавляет устройства, если мои сценарии УДЯ начинаются на ХА

### ISSUE THREAD

**Issue by mad0k** [AlexxIT/YandexStation#236]
Интеграция не добавляет устройства, если в УДЯ имеется сценарий (помимо служебного), начинающийся на "ХА ".
В журнал ХА сразу сыпет ошибками:
```
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:46
Integration: Медиаплеер (documentation, issues)
First occurred: 22:13:24 (1 occurrences)
Last logged: 22:13:24

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 84, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 99, in load_speakers
    scenarios = await self.load_scenarios()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 128, in load_scenarios
    return {
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 129, in <dictcomp>
    decode(d['name']): d
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 46, in decode
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 46, in <listcomp>
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
ValueError: substring not found
```

Посмотрел функцию decode и ту, что ее вызывает, стало понятно в чем косяк.
Возможно в инструкции стоит упомянуть, что сценарии УДЯ нельзя называть "ХА блаблабла".

**Comment by AlexxIT** [comment]
Не думал, что кому-то прийдёт в голову так назвать сценарии

**Comment by camohob** [comment]
я тоже попался

**Comment by AlexxIT** [comment]
Поправлено в последнем мастере. Будет в следующем релизе
