### ISSUE TITLE
Не синхронизируется список покупок

### ISSUE THREAD

**Issue by vvoolfie** [AlexxIT/YandexStation#240]
Станция lite
Скрипт:
```
alias: Обновить список покупок
sequence:
  - service: media_player.play_media
    entity_id: media_player.yandex_station_lite_kitchen
    data:
      media_content_id: update
      media_content_type: shopping_list
mode: single
```

Ошибка при трассировке
```
Stopped because an error was encountered at 31 января 2022 г., 00:27:10 (runtime: 6.00 seconds)

'NoneType' object is not subscriptable
```

Лог
```
- TypeError: 'NoneType' object is not subscriptable
2022-01-31 00:02:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547232636784] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 273, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 377, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 403, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/yandex_station/media_player.py", line 826, in async_play_media
    await self._shopping_list()
  File "/config/custom_components/yandex_station/media_player.py", line 329, in _shopping_list
    alice_list = RE_SHOPPING.findall(card['text'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AlexxIT** [comment]
Регулярно повторяется или случайно возникла?

**Comment by vvoolfie** [comment]
Регулярно, с момента настройки

**Comment by Angus774** [comment]
Такая же проблема

**Comment by ClusterM** [comment]
И у меня.

**Comment by JohnyVLive** [comment]
Подтверждаю

**Comment by bartlebi** [comment]
+1 проблема актуальна. Причем ещё неделю назад он работал, но стоило переехать из докера в виртуалку и оно перестало синхронизироваться. При этом колонка список проговаривает при выполнении скрипта, но синхронизации нет и в логах также ошибка. Возможно ещё связано со сменой авторизации, до переезда она была через ямл, а после перенастроил через куэр.

**Comment by ClusterM** [comment]
Я потыкал API, и похоже, что список покупок теперь в принципе нельзя перехватить.

**Comment by chmutoff** [comment]
> Я потыкал API, и похоже, что список покупок теперь в принципе нельзя перехватить.

Как так то? Может можно создать похожий навык, типа "Нормальный список покупок"?

На Lite колонке тоже не работает

**Comment by bartlebi** [comment]
Насколько я разобрался в коде, там общение через отсылку текста происходит и никакого апи для списка покупок нет. Видимо что-то поменялось в диалогах у Алисы. Но может я и не прав, из меня программист не оч:)

**Comment by chmutoff** [comment]
> Насколько я разобрался в коде, там общение через отсылку текста происходит и никакого апи для списка покупок нет. Видимо что-то поменялось в диалогах у Алисы. Но может я и не прав, из меня программист не оч:)

Да, проблема вот в этом месте:
`media_player.py` строка 327
```
        card = await self.glagol.send({'command': 'sendText',
                                       'text': "Что в списке покупок"})
        alice_list = RE_SHOPPING.findall(card['text'])
        self.debug(f"Список покупок: {alice_list}")
```
В 327 строчке после запроса списка покупок Алиса произносит список на колонке но вызов glagol.send возвращает `None` и собственно при дальнейшем использовании `None` питон ругается.

**Comment by Evgen-BioNik** [comment]
Такая же проблема.

**Comment by artt652** [comment]
Same issue.

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:861
Integration: Yandex.Station (documentation, issues)
First occurred: 23:16:27 (3 occurrences)
Last logged: 23:17:42

Unsupported cloud media: shopping_list

**Comment by AlexxIT** [comment]
На данный момент синхронизация списка покупок работает
