### ISSUE TITLE
Ошибка запуска интеграции

### ISSUE THREAD

**Issue by Moscowbikerboy** [AlexxIT/YandexStation#254]
```
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_session.py:463
Integration: Медиаплеер ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 21:06:12 (1 occurrences)
Last logged: 21:06:12

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 84, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 103, in load_speakers
    scenarios = await self.load_scenarios()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 128, in load_scenarios
    r = await self.session.get(f"{URL_USER}/scenarios")
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 420, in get
    return await self._request('get', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 461, in _request
    return await self._request(method, url, retry - 1, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 461, in _request
    return await self._request(method, url, retry - 1, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 463, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https: //iot.quasar.yandex.ru/m/user/scenarios return 500 status
````

**Comment by AlexxIT** [comment]
Какой-то глюк на серверах Яндекса. Учитывая, что это запрос на получение списка сценариев без всяких параметров - невозможно починить со стороны интеграции
