### ISSUE TITLE
Не работает воспроизведение с заданной громкостью

### ISSUE THREAD

**Issue by mzhur** [AlexxIT/YandexStation#267]
Ошибка в log Home assistant
Logger: custom_components.yandex_station.core.yandex_glagol
Source: custom_components/yandex_station/media_player.py:390
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 22:00:52 (6 occurrences)
Last logged: 22:03:22

Яндекс Станция | Station connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/core/yandex_glagol.py", line 127, in _connect
    self.update_handler(data)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/media_player.py", line 500, in async_set_state
    self._process_alice_volume(state['aliceState'])
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/media_player.py", line 390, in _process_alice_volume
    volume = self.alice_volume['prev_volume']
KeyError: 'prev_volume'

Action  в автоматизациях, который запускает tts, раньше работал
 action:
  - data_template:
      media_content_id: <speaker effect="megaphone">'Мы всё еще ждем у двери! Откройте нам!'
      media_content_type: text
      extra:
          volume_level: 0.9
    entity_id: media_player.yandex_station_xxx
    service: media_player.play_media
  mode: single

**Comment by EniseiDev** [comment]
Аналогичная проблема. Есть мысль, что это возникло при обновлении HA до версии 2.4.x.

**Comment by mzhur** [comment]
У меня возникла примерно неделю назад. HA не обновлял точно. Возможно обновил компонент. Не сразу заметил, только когда сработала автоматизация....

**Comment by mzhur** [comment]
Аналогичный issue
https://github.com/AlexxIT/YandexStation/issues/253
