### ISSUE TITLE
Ошибка при отсутствии обложки

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/YandexStation#274]
ХА выкидывает ошибку, если у композиции по какой то причине нет обложки. 

Версия компонента - последняя.
Версия ХА - последняя.

текст ошибки

```
2022-05-30 14:40:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yarl/_url.py", line 170, in __new__
    port = val.port
  File "/usr/local/lib/python3.9/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '8123https:'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.9/site-packages/yarl/_url.py", line 172, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1086, in get
    data, content_type = await player.async_get_media_image()
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 530, in async_get_media_image
    return await self._async_fetch_image_from_cache(url)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1009, in _async_fetch_image_from_cache
    (content, content_type) = await self._async_fetch_image(url)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1020, in _async_fetch_image
    return await async_fetch_image(_LOGGER, self.hass, url)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1217, in async_fetch_image
    response = await websession.get(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 424, in _request
    raise InvalidURL(str_or_url) from e
aiohttp.client_exceptions.InvalidURL: http://192.168.1.14:8123https://
```

и вот что в сущности

```
source_list: Станция
volume_level: 0.5
is_volume_muted: false
media_content_type: music
media_duration: 147
media_position: 44
media_position_updated_at: 2022-05-30T11:32:09.550477+00:00
media_title: Ланфрен-ланфра
media_artist: Михаил Боярский
source: Станция
entity_picture_local: /api/media_player_proxy/media_player.yandex_v?token=21d63c5fc2022487e7679c3ad46192c3ea3458c55d9f617a3db5a112871aa9b3&cache=66dfeeedabf1f022
alice_state: IDLE
device_class: tv
entity_picture: https://
friendly_name: Yandex V
supported_features: 151487
```

**Comment by AlexxIT** [comment]
Не смог повторить, чинил вслепую
