### ISSUE TITLE
Integration doesn't let to login.

### ISSUE THREAD

**Issue by Pansovi4** [AlexxIT/YandexStation#281]
Integration worked ok. 2 weeks ago got error - object *unavailable*
Tried to re-install integration.
Now  I am getting error after login: *Unknown error occurred*
I turned on 2-factor authentificaton, installed yandex-key app on phone - still error logging in.
I tried all options like temp key/qr code/ login+pass - the same error.

By the way I can login into yandex account on pc or phone and i can see attempts to login in login history.
I am located in Estonia - can it be the reason?

**Comment by devbis** [comment]
I tried to login with email and have the same problem.
Here is a log chunk from HA:

```
  File "/home/homeassistant/homeassistant/custom_components/yandex_station/config_flow.py", line 118, in async_step_email2
    resp = await self.yandex.login_letter()
  File "/home/homeassistant/homeassistant/custom_components/yandex_station/core/yandex_session.py", line 274, in login_letter
    return await self.login_cookies()
  File "/home/homeassistant/homeassistant/custom_components/yandex_station/core/yandex_session.py", line 338, in login_cookies
    x_token = resp["access_token"]
KeyError: 'access_token'
```

**Comment by Pansovi4** [comment]
> I tried to login with email and have the same problem. Here is a log chunk from HA:
> 
> ```
>   File "/home/homeassistant/homeassistant/custom_components/yandex_station/config_flow.py", line 118, in async_step_email2
>     resp = await self.yandex.login_letter()
>   File "/home/homeassistant/homeassistant/custom_components/yandex_station/core/yandex_session.py", line 274, in login_letter
>     return await self.login_cookies()
>   File "/home/homeassistant/homeassistant/custom_components/yandex_station/core/yandex_session.py", line 338, in login_cookies
>     x_token = resp["access_token"]
> KeyError: 'access_token'
> ```

Добрый день, у вас так и не получилось залогиниться? Я уже с нуля всё проставил, так и без шансов.

**Comment by devbis** [comment]
Я с тех пор не пытался залогиниться. Пока неактуально, потому не проверял.

**Comment by Pansovi4** [comment]
По прежнему не пускает, вот лог ошибки после логина по QR code

Уровень: ОШИБКА

Эта ошибка возникла в кастомной интеграции.
Logger: aiohttp.server
Source: custom_components/yandex_station/core/yandex_session.py:326
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 11:03:54 (2 occurrences)
Last logged: 11:04:43

Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/yandex_station/config_flow.py", line 101, in async_step_auth
resp = await self.yandex.login_password(user_input['password'])
File "/config/custom_components/yandex_station/core/yandex_session.py", line 170, in login_password
return await self.login_cookies()
File "/config/custom_components/yandex_station/core/yandex_session.py", line 326, in login_cookies
r = await self.session.post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobileproxy.passport.yandex.net:443 ssl:default [Connect call failed ('127.0.0.1', 443)]

**Comment by devbis** [comment]
@Pansovi4 Судя по логу у тебя на сервере с ХА проблема с подключением. Попробуй отключить впн или наооборот включить.

**Comment by AlexxIT** [comment]
@Pansovi4 обычные проблемы с интернетом. Интеграция тут ничего не сможет сделать

**Comment by AlexxIT** [comment]
Здесь никакой магии быть не может. Ваш браузер может достучаться до сервера Яндекса, а ваш сервер ХА - не может. 

Кстати зря вы замазали IP сервера Яндекса. Он не секретный.
И похоже у вас он неверный https://www.reg.ru/nettools/dig?domain=mobileproxy.passport.yandex.net&type=any&dns=

**Comment by Radiomix2000** [comment]
> Здесь никакой магии быть не может. Ваш браузер может достучаться до сервера Яндекса, а ваш сервер ХА - не может.
> 
> Кстати зря вы замазали IP сервера Яндекса. Он не секретный. И похоже у вас он неверный https://www.reg.ru/nettools/dig?domain=mobileproxy.passport.yandex.net&type=any&dns=

Замазан мой IP, а не Яндекса. К тому же зачем там быть IP яндекса, если у него есть доменное имя.
Ваш ответ прям в стиле поддержки этого самого яндекса)
Для работы ХА IP яндекса вообще не нужен, повторяю, есть  доменные имена. Более того, никакой IP  яндекса нигде не вводился при конфигурации плагина. Вы это должны сами, как автор, знать. Я даже понятия не имею, какие там у яндекса IP.
Просто всё работало прекрасно, потом в один вечер колонка перестала выполнять действия по голосовой команде, полез разбираться, а там такая фигня.
Ну ладно, я уже понял, что ответа не получу здесь. Больше не буду тратить ваше и своё время. 
Спасибо. Буду разбираться, если раберусь. Ну не так нет.

**Comment by Radiomix2000** [comment]
ах вот в чём проблема:
https://ttja.ee/ru/dostup-k-saytu-vremenno-ogranichen
Сюда перенаправляют с адреса mobileproxy.passport.yandex.net
наши "демократические" блюстители свободы в очередной раз выстрелили себе в ногу.
Е6аноиды.
Поэтому и IP там неправильный.
