### ISSUE TITLE
Яндекс-мини-2 не показывается информация о треке

### ISSUE THREAD

**Issue by kaizer666** [AlexxIT/YandexStation#306]
Включаю свой плейлист (или любую другую музыку) - на карточке Яндекс станции мини 2 (с часами) не показывается информация. Кнопки все работают, но информации нет. На Яндекс станции (1 поколение, большая) - всё отлично с теми же треками и плейлистами. В логах такая ошибка:

```
Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_services/browser.py", line 533, in run
    self._fire_service_state_changed_event(event)
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_services/browser.py", line 416, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 251, in _zeroconf_handler
    'device_id': properties['deviceId'],
KeyError: 'deviceId'
```

**Comment by AlexxIT** [comment]
Фикс в мастер-версии. Попадёт в следующий релиз

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.0
