### ISSUE TITLE
Termex if pro wifi

### ISSUE THREAD

**Issue by sergt1978** [AlexxIT/YandexStation#308]
После ввода в удя, управление есть. При подключении интеграции в на водонагреватель подттянулся как climate. При включенном состоянии статус в на uknown в выключенном состоянии off. Управление вкл/выкл в на отсутствует, хотя ругулировка температуры двусторонняя работает и из на в удя и из него в на

**Comment by sergt1978** [comment]
Update for climate.vodonagrevatel fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 717, in async_device_update
    await task
  File "/config/custom_components/yandex_station/climate.py", line 165, in async_update
    data = await self.quasar.get_device(self.device['id'])
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 300, in get_device
    r = await self.session.get(f"{URL_USER}/devices/{deviceid}")
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 420, in get
    return await self._request('get', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 445, in _request
    r = await getattr(self.session, method)(url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host iot.quasar.yandex.ru:443 ssl:default [Network unreachable]

**Comment by sergt1978** [comment]
Update for climate.vodonagrevatel fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 717, in async_device_update
    await task
  File "/config/custom_components/yandex_station/climate.py", line 165, in async_update
    data = await self.quasar.get_device(self.device['id'])
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 300, in get_device
    r = await self.session.get(f"{URL_USER}/devices/{deviceid}")
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 420, in get
    return await self._request('get', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 445, in _request
    r = await getattr(self.session, method)(url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by sergt1978** [comment]
прилагаю лог ошибок

**Comment by AlexxIT** [comment]
"Cannot connect to host" - проблемы с интернетом. Интеграция не может с этим что-то сделать
