### ISSUE TITLE
Активационная фраза для сценария уже используется

### ISSUE THREAD

**Issue by promo148** [AlexxIT/YandexStation#323]
Помогите разобраться, отвалилась колонка в HA. Раньше всё работало. Не могу понять в чем причина.

Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:171
Integration: Медиаплеер (documentation, issues)
First occurred: 14 ноября 2022 г., 00:12:07 (5 occurrences)
Last logged: 00:49:39

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 97, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 112, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 171, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '94b579b4-bc6d-4ce5-89e9-f759f7aed914', 'status': 'error', 'code': 'VOICE_TRIGGER_PHRASE_IS_ALREADY_TAKEN', 'message': 'Активационная фраза для сценария уже используется'}

**Comment by slgeo** [comment]
Зайдите в интерфейс Квазар и удалите в сценариях, созданные не вами. У меня мешали нормальной работе сценарии, автоматически созданные Majordomo.

**Comment by AlexxIT** [comment]
#157 #193
