### ISSUE TITLE
ServerDisconnectedError

### ISSUE THREAD

**Issue by AlexeyZhukoff** [AlexxIT/YandexStation#33]
Здравствуйте, часто появляются ошибки в логе, после этого нагрузка на процессор возрастает, до перезагрузки "HA".
Home assistant крутится в докере.
По конфигурации у меня одна Яндекс станция и три Мини.

Не самая частая:
```
Уровень: ERROR
Logger: custom_components.yandex_station.yandex_glagol
Source: custom_components/yandex_station/yandex_glagol.py:58
Integration: YandexStation (documentation)
First occurred: 4:47:53 (4 occurrences)
Last logged: 5:49:11

Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_glagol.py", line 58, in _connect
    self.ws = await session.ws_connect(uri, heartbeat=55, ssl=False)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 728, in _ws_connect
    proxy_headers=proxy_headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

Самая частая:
```
Уровень: ERROR
Logger: custom_components.yandex_station.yandex_glagol
Source: custom_components/yandex_station/yandex_glagol.py:89
Integration: YandexStation (documentation)
First occurred: 2:27:37 (20 occurrences)
Last logged: 6:02:30

Station connect error [None] Cannot connect to host 192.168.1.21:1961 ssl:False [None]
Station connect error [113] Cannot connect to host 192.168.1.21:1961 ssl:False [Connect call failed ('192.168.1.21', 1961)]
Station connect error [111] Cannot connect to host 192.168.1.21:1961 ssl:False [Connect call failed ('192.168.1.21', 1961)]
Station connect error [110] Cannot connect to host 192.168.1.21:1961 ssl:False [Connect call failed ('192.168.1.21', 1961)]
```

**Comment by ixkor** [comment]
У меня тоже такая ошибка, возрастание нагрузки на проц не мониторил. У меня ошибка кажется связана с тем что у станции похоже иногда меняется локальный IP (при том что на роутере назначил ей статический кстати). Надо бы добавить обновление адреса устройства периодическое или при ошибке (или нескольких подряд) подключения. Попробую на выходных сделать и оформить пулл реквест.

**Comment by AlexxIT** [comment]
Не актуально
