### ISSUE TITLE
Нельзя добавлять в сценарии чужие устройства. Пожалуйста, удалите их из сценария и попробуйте еще раз.

### ISSUE THREAD

**Issue by dE1l** [AlexxIT/YandexStation#339]
Около года пользуюсь интеграцией. Но тут столкнулся с ошибкой, интеграция перестала работать:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 149, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-02-08 15:56:22.945 WARNING (MainThread) [custom_components.yandex_station.select] Не удалось загрузить эквалайзер
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/select.py", line 69, in async_update
    conf: dict = await self.quasar.get_device_config(self.device)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 280, in get_device_config
    r = await self.session.get(
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 420, in get
    return await self._request('get', url, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 461, in _request
    return await self._request(method, url, retry - 1, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 461, in _request
    return await self._request(method, url, retry - 1, **kwargs)
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 463, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://quasar.yandex.ru/get_device_config return 403 status
2023-02-08 15:56:23.380 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 97, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 112, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 171, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '3929c593-****-****-****-729d3514b75f', 'status': 'error', 'code': 'SHARED_DEVICE_USED_IN_SCENARIO', 'message': 'Нельзя добавлять в сценарии чужие устройства. Пожалуйста, удалите их из сценария и попробуйте еще раз.'}
```

Долго разбирался.. Оказалось, что проблема была в том, что я в приложении Умный дом добавил себе ещё один ДОМ, владельцем которого я не являюсь, но могу управлять. На меня его расшарили.

В итоге при инициализации интеграции мне отображались 3 колонки мои и одна "чужая".
При этом, я просто использовал официальный функционал по его прямому назначению - мне дали доступ к родительскому дому.

Подчеркну: никаких чужих устройств в сценариях не было. Это сильно ввело в заблуждение при поисках причины. Был лишь добавлен новый дом через функцию "Пригласить новых людей".

Ожидаемое поведение: не падать с ошибкой, а игнорировать "чужое" устройство при инициализации и работать без него.

**Comment by AlexxIT** [comment]
#317
