### ISSUE TITLE
unauthorized_client

### ISSUE THREAD

**Issue by VGorokhov** [AlexxIT/YandexStation#34]
Уровень: ERROR
Logger: custom_components.yandex_station.yandex_quasar
Source: custom_components/yandex_station/yandex_quasar.py:143
Integration: yandex_station
First occurred: 18:59:26 (1 occurrences)
Last logged: 18:59:26

Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 69, in init
    self.main_token = await self.get_main_token(username, password)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 143, in get_main_token
    assert 'access_token' in resp, resp
AssertionError: {'error': 'unauthorized_client'}

Удаление файла с расширение .json из папки yandex_station, с последующем перезапуском HA также не решило проблему. Выскакивает таже ошибка.

**Comment by AlexxIT** [comment]
https://t.me/AlexxIT_SmartHome/152

**Comment by AlexxIT** [comment]
Поправлено https://github.com/AlexxIT/YandexStation/releases/tag/v2.0.3

**Comment by devbis** [comment]
Такая же ошибка на последней версии из master.
Похоже, что не исправлено.

**Comment by AlexxIT** [comment]
@devbis проверил, всё норм. Как была установлена версия? HACS иногда глючит и может не обновить версию. Даже если и говорит, что обновил.

**Comment by devbis** [comment]
Переустанавливаю с нуля home-assistant.
homeassistant==0.111.4 установлено в virtualenv
YandexStation склонирован из гита (master) и скопирован в папку custom_components
В конфигурации подключено:
```
yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password
  tts_service_name: alice_say
```

В логах при старте получаю 

```
 2020-06-26 11:19:50 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
 Traceback (most recent call last):
   File "/home/homeassistant/.homeassistant/custom_components/yandex_station/yandex_quasar.py", line 69, in init
     self.main_token = await self.get_main_token(username, password)
   File "/home/homeassistant/.homeassistant/custom_components/yandex_station/yandex_quasar.py", line 143, in get_main_token
     assert 'access_token' in resp, resp
 AssertionError: {'error': 'unauthorized_client'}
 2020-06-26 11:19:50 ERROR (MainThread) [custom_components.yandex_station.utils] В аккаунте нет устройств
```

**Comment by AlexxIT** [comment]
Там я с гитом немного накосячил. В мастере была старая версия. Новая версия была в последнем релизе - 2.0.3
Кто пользовался именно релизами (как и рекомендуется) - всё норм.
Поправил. Теперь и в мастере новая логика авторизации.
