### ISSUE TITLE
Can't get zeroconf info

### ISSUE THREAD

**Issue by dpetrovichev** [AlexxIT/YandexStation#344]
```
Logger: custom_components.yandex_station.core.yandex_glagol
Source: custom_components/yandex_station/core/yandex_glagol.py:237
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 03:08:15 (1 occurrences)
Last logged: 03:08:15

Can't get zeroconf info
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_utils/asyncio.py", line 86, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 237, in _zeroconf_handler
    info = zeroconf.get_service_info(service_type, name)
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_core.py", line 540, in get_service_info
    if info.request(self, timeout, question_type):
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_services/info.py", line 482, in request
    return bool(run_coro_with_timeout(self.async_request(zc, timeout, question_type), zc.loop, timeout))
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_utils/asyncio.py", line 90, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.0
