### ISSUE TITLE
Ошибка инициализации интеграции при наличии гостевого доступа к чужим домам со своими Яндекс.Станциями

### ISSUE THREAD

**Issue by realbigest** [AlexxIT/YandexStation#346]
В приложении Умного дома Яндекс есть возможность предоставить доступ к управлению устройствами умного дома другому аккаунту. Если воспользоваться ей и получить гостевой доступ к чужому дому, в котором есть своя Яндекс.Станция, то интеграция YandexStation начинает падать при инициализации со следующей ошибкой:

```
Уровень: ОШИБКА

Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:171 
Integration: Медиаплеер ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22)) 
First occurred: 09:48:20 (4 occurrences) 
Last logged: 09:52:42

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 97, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 112, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 171, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '00000000-0000-0000-0000-00000000000', 'status': 'error', 'code': 'SHARED_DEVICE_USED_IN_SCENARIO', 'message': '**Нельзя добавлять в сценарии чужие устройства. Пожалуйста, удалите их из сценария и попробуйте еще раз.**'}
```

**Comment by AlexxIT** [comment]
#317
