### ISSUE TITLE
После обновления компонента, в журнале ошибки

### ISSUE THREAD

**Issue by Dasisfakt** [AlexxIT/YandexStation#352]
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 02:14:21 (8 occurrences)
Last logged: 02:14:21

Error unloading entry Яндекс Станция for switch
Error unloading entry Яндекс Станция for vacuum
Error unloading entry Яндекс Станция for humidifier
Error unloading entry Яндекс Станция for sensor
Error unloading entry Яндекс Станция for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 201, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by AlexxIT** [comment]
Компонент не смог выгрузиться. Но мы не знаем, почему он не загрузился. Поэтому такую ошибку невозможно починить.
