### ISSUE TITLE
Ошибка после обновления 3.12: KeyError: 'quasar_info'

### ISSUE THREAD

**Issue by kostenkodm** [AlexxIT/YandexStation#353]
```
Logger: homeassistant.config_entries
Source: custom_components/yandex_station/__init__.py:142
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 10:55:29 (1 occurrences)
Last logged: 10:55:29

Error setting up entry diman.molotov for yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yandex_station/__init__.py", line 142, in async_setup_entry
    did = device["quasar_info"]["device_id"]
KeyError: 'quasar_info'
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.1
