### ISSUE TITLE
Не определяются колонки - ошибка инициализации yandex_station

### ISSUE THREAD

**Issue by toxig** [AlexxIT/YandexStation#373]
Пропали все колонки из интеграции yandex_station

Ошибки в логе:
`
2023-05-23 20:45:59.742 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 128, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 124, in load_speakers
    scenario = next(
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 125, in <genexpr>
    v for k, v in scenarios.items() if device_id.startswith(k)
TypeError: startswith first arg must be str or a tuple of str, not NoneType
`

**Comment by toxig** [comment]
Причина:
* ошибка загрузки служебных автоматизаций в яндекс доме (https://yandex.ru/quasar/iot)
* служебные интеграции начинаются на ХА (пример "ХА тнаупусяылеаиынссвымса")
* в список интеграций ранее вручную добавил команду начиная с префикса "ХА ..." которая вызывала сбой

![image](https://github.com/AlexxIT/YandexStation/assets/377486/eeb278c0-4471-4ede-ad85-d7c35b392ffb)

Решение: удалить/переименовать лишние интеграции с префиксом "ХА "
