### ISSUE TITLE
при инициализции ошибка: в аккаунте нет устройств

### ISSUE THREAD

**Issue by svsolopov** [AlexxIT/YandexStation#38]
До обновления компонента все работало через токен (яндекс станция большая), после стала выдавать ошибку медиаплеера что нет токена, сессион ид.

Поменял авторизацию на логин пароль и получил ошибку: в аккаунте нет устройств

**Comment by AlexxIT** [comment]
Выпустил v2.2.2, может поможет. Работу только по токену проверил - работает без ошибок.

**Comment by Zhappa** [comment]
та же проблема с 2.2.2

**Comment by Zhappa** [comment]
с версией 2.1.0 такая же штука, может что-то на стороне яндекса?

**Comment by Zhappa** [comment]
2020-07-08 14:02:33 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 78, in init
    self.main_token = await self.get_main_token(username, password)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 166, in get_main_token
    assert 'x_token' in resp, resp
AssertionError: {'status': 'error', 'errors': ['account.not_found']}
2020-07-08 14:02:33 ERROR (MainThread) [custom_components.yandex_station.utils] В аккаунте нет устройств
2020-07-08 14:02:33 ERROR (MainThread) [homeassistant.setup] Setup failed for yandex_station: Integration failed to initialize.

**Comment by Zhappa** [comment]
Использую оригинальные имя-пароль, двухэтапная аутентификация отключена

**Comment by AlexxIT** [comment]
@Zhappa Яндекс говорит, что в имени пользователя ошибка. Проверьте на опечатки. Может в двойные кавычки его взять

**Comment by Zhappa** [comment]
Перепроверил логин и оказалось переставил местами символы. После того как исправил - заработало, версия 2.2.2
Спасибо!

**Comment by svsolopov** [comment]
заработало, спасибо
