### ISSUE TITLE
Не удается добавить Станции после авторизации

### ISSUE THREAD

**Issue by x-iLex-x** [AlexxIT/YandexStation#385]
Версия: 3.12.3

Проблема:
После авторизации не подтягиваются колонки, висит ошибка "Не удалось настроить \ нет устройств или объектов"

Предшествующие действия:
Появилась необходимость удалить интеграцию и установить заново.

Порядок действий:
Удаление записей интеграции - Удаление интеграции из HACS - Перезапуск HA - Установка интеграции в HACS - Перезапуск HA - Поиск и настройка интеграции через раздел интеграций - Авторизация в аккаунте

Лог:

```
Logger: homeassistant.config_entries
Source: custom_components/yandex_station/core/yandex_session.py:481
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 16:36:21 (4 occurrences)
Last logged: 16:36:48

Error setting up entry prodih for yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/__init__.py", line 134, in async_setup_entry
    await quasar.init()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 82, in init
    r = await self.session.get(f"{URL_V3_USER}/devices")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 439, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 479, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 479, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 481, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/v3/user/devices return 401 status
```

**Comment by diHousePRO** [comment]
upd:

Станции подтянулись сразу же после того, как я переименовал запись интеграции с логина на другое название ("Яндекс Станции").

**Comment by bob24682** [comment]
тоже самое:   авторизация проходит а станция не находится.
переименование и прочие танцы пока не помогли


Logger: homeassistant.config_entries
Source: custom_components/yandex_station/core/yandex_session.py:511
Integration: Yandex.Station (documentation, issues)
First occurred: 17:41:40 (1 occurrences)
Last logged: 17:41:40

Error setting up entry Яндекс Станции for yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/__init__.py", line 137, in async_setup_entry
    await quasar.init()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 82, in init
    r = await self.session.get(f"{URL_V3_USER}/devices")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 465, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 509, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 509, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 511, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/v3/user/devices return 401 status

**Comment by freefelt** [comment]
> upd:
> 
> Станции подтянулись сразу же после того, как я переименовал запись интеграции с логина на другое название ("Яндекс Станции").

Привет! Что значит "переименовал запись интеграции с логина на другое название"?

**Comment by x-iLex-x** [comment]
> > upd:
> > Станции подтянулись сразу же после того, как я переименовал запись интеграции с логина на другое название ("Яндекс Станции").
> 
> Привет! Что значит "переименовал запись интеграции с логина на другое название"?

Приветствую! Вот так :)

![IMG_5625](https://github.com/AlexxIT/YandexStation/assets/130607708/ca7b1eda-9301-4821-9dd4-cc7d59ec943a)
![IMG_5626](https://github.com/AlexxIT/YandexStation/assets/130607708/20837c27-90df-4bb4-9519-0a866f82ddb8)

**Comment by Medas999** [comment]
Ничего из выше перечисленного не помогает задолбался уже
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/yandex_station/__init__.py", line 124, in async_setup_entry
ok = await yandex.refresh_cookies()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/yandex_station/core/yandex_session.py", line 427, in refresh_cookies
r = await self.session.get(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
conn = await self._connector.connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
proto = await self._create_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
sock = await self._connect_sock(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
return await fut

**Comment by AlexxIT** [comment]
Так понимаю проблема решена

**Comment by Denis021188** [comment]
У меня так же и не решается и переименовать не помогло. установил прошлую версию интеграции по работало два дня ушло в недоступно удали сново залогинелся и видит только один обьект эквалайзер. что делать( всю голову сломал
