### ISSUE TITLE
Ошибка в декодировании json

### ISSUE THREAD

**Issue by MihVS** [AlexxIT/YandexStation#390]
Здравствуйте, колонки не стали управляться с помощью конфига:
```
- service: yandex_station.send_command
      entity_id:  media_player.yandex_station_xxxxxxxxxxxx
      data:
          command: stop
```
<details>
<summary>В логах НА следующая ошибка:</summary>
```
Эта ошибка возникла в пользовательской интеграции.
Logger: custom_components.yandex_station.core.yandex_glagol
Source: helpers/aiohttp_client.py:72
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 16:11:54 (2 occurrences)
Last logged: 16:11:54

Яндекс Мини | Station connect
Яндекс Станция Макс | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 89, in _connect
    self.device_token = await self.get_device_token()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 59, in get_device_token
    resp = await r.json()
           ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 72, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://quasar.yandex.net/glagol/token?device_id=FF98F029B090CE3FC751732A&platform=yandexmini')
```

**Comment by AlexxIT** [comment]
#389
