### ISSUE TITLE
Получаю ошибку yandex_tts1: Error executing script. Unexpected error for call_service at pos 1

### ISSUE THREAD

**Issue by mishganze** [AlexxIT/YandexStation#399]
Вот что пишет в логи
```
yandex_tts1: Error executing script. Unexpected error for call_service at pos 1: https://iot.quasar.yandex.ru/m/user/scenarios/19d9f2af-349b-4195-a0d7-6555904f8b5b return 404 status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/yandex_station/media_player.py", line 958, in async_play_media
    await self.quasar.send(self.device, media_id, is_tts=True)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 279, in send
    r = await self.session.put(f"{URL_USER}/scenarios/{sid}", json=payload)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 471, in put
    return await self._request("put", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 509, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 509, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 511, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/user/scenarios/19d9f2af-349b-4195-a0d7-6555904f8b5b return 404 status
```

**Comment by mishganze** [comment]
Скрипт выполняю такой. 
`script:
  yandex_tts1:
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station_xxxxxxxxxxxxxxxxxxxxxxxxxx
      data:
        media_content_id: 'Температура в комнате {{ states("sensor.temperature_hall")|round }} градуса'
        media_content_type: text`
Остальные функции yandex station  функционируют нормально

**Comment by AlexxIT** [comment]
Вероятно вы самостоятельно удалили важный сценарий из умного дома Яндекса

**Comment by 0kay64** [comment]
Здравствуйте, похоже, я тоже совершил ошибку, не подумав, и удалил из умного дома Яндекс сценарий с какой-то абракадаброй. После этого пошли ошибки https://iot.quasar.yandex.ru/m/user/scenarios/*** return 404 status и алиса перестала произносить фразы. Возникает вопрос, а как теперь его восстановить.

**Comment by AlexxIT** [comment]
Для восстановления сценариев нужно перезагрузить интеграцию или ХА.
