### ISSUE TITLE
Периодические ошибки в логах

### ISSUE THREAD

**Issue by p1ne** [AlexxIT/YandexStation#401]
Лог с включенным logger: custom_components.yandex_station: debug
```
2023-10-26 15:53:14.010 WARNING (MainThread) [custom_components.yandex_station.core.utils] Can't get media_players
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/utils.py", line 368, in get_media_players
    conf = hass.data[DOMAIN][DATA_CONFIG].get(CONF_MEDIA_PLAYERS)
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-10-26 15:53:14.014 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/__init__.py", line 188, in found_local_speaker
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 756, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for 
```
Колонок три - самая первая большая Станция, станция мини2 с часами и Xiaomi-станция с экраном

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.5
