### ISSUE TITLE
Ошибка просмотра медиа после обновления HA Core 2024.1.0

### ISSUE THREAD

**Issue by Prozorovshurik** [AlexxIT/YandexStation#430]
При попытке войти в диалоговое окно просмотр медиа, плеера Yandex mini 2, HA выдаёт ошибку Ошибка просмотра Мультимедиа: Unknown error. 

При этом в логах следующая запись:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/media_player/__init__.py:1298
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:37:35 (23 occurrences)
Last logged: 11:17:49

[281472913946816] Error handling message: Unknown error (unknown_error) Prozorov Alexander from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
[281472400205504] Error handling message: Unknown error (unknown_error) Prozorov Alexander from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
[281472479829440] Error handling message: Unknown error (unknown_error) Prozorov Alexander from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

![image](https://github.com/AlexxIT/YandexStation/assets/58695099/c038b40e-0e26-4675-8153-6a0d4002bb5f)

На втором не обновлённом HA ошибки нет

**Comment by Roman-RV78** [comment]
Подтверждаю. Такая же ошибка.

**Comment by golovopatolog** [comment]
Такая же фигулина

**Comment by SSG099** [comment]
Присоединяюсь

**Comment by kpe03031973** [comment]
Такая же ошибка. и на Core 2024.1.1 то же

**Comment by AndreiCh74** [comment]
Тоже самое.  Core 2024.1.1

**Comment by ChapayTv** [comment]
Подтверждаю ошибку

**Comment by a-x-** [comment]
@AlexxIT если подскажете где смотреть и как примерно чинить могу сделать PR

**Comment by MikhailTeddy** [comment]
То же и на 2024.1.2. Не работает карточка телевизора (media_player..) с Яндекс ИК пульта, из умного дома Я. Не работает "Браузер медиа для плагина Yandex Station" https://github.com/alryaz/hass-yandex-music-browser (но это наверное надо написать altyaz}. Не работала интеграция "Яндекс погода", но автор вчера обновление выпустил под 2024 - https://github.com/IATkachenko/HA-YandexWeather.
  Логи к сожалению показать не могу, откатился к 2023.12.4

**Comment by kai-zer-ru** [comment]
Присоединяюсь. Не работает. 

```
[139625620139968] Error handling message: Unknown error (unknown_error) Максим from 192.168.1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.714 YaBrowser/23.11.1.714 Yowser/2.5 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by a-x-** [comment]
А с Алексом все в порядке? Канал в телеге уже давно не обновляется как будто

**Comment by golovopatolog** [comment]
Отдыхает наверное человек, как все)

**Comment by Tynianoff** [comment]
Подтверждаю проблему

**Comment by gfrantsau** [comment]
такая же проблема

**Comment by Roman-RV78** [comment]
Расходимся))). После нового релиза YandexStation всё заработало. Алексу спасибо!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
