### ISSUE TITLE
Не добавляется телевизор из УДЯ в HA

### ISSUE THREAD

**Issue by samplec0de** [AlexxIT/YandexStation#431]
Привет! Раньше работало, можно было пробросить из умного дома яндекса в HA телек (подключен через IR Broadlink). Сейчас выдает ошибку. 

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:368
Integration: Медиа плеер (documentation, issues)
First occurred: 21:00:51 (1 occurrences)
Last logged: 21:00:51

```
Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1094, in capability_attributes
    source_list := self.source_list
                   ^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/media_player.py", line 1172, in source_list
    return list(self._sources.keys())
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by AlexxIT** [comment]
Нужно проверить в последнем релизе. Если есть проблемы - приложить диагностику устройства из ХА
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0

**Comment by iEBPO** [comment]
У меня заработало после обновления.
