### ISSUE TITLE
Aqara E1 Thermostat - не передаются значения HVAC mode

### ISSUE THREAD

**Issue by Leviann** [AlexxIT/YandexStation#432]
При добавлении термостата Aqara E1, модель SRTS-A01, не передаются значения hvac. Что, в целом, ожидаемо, так как в приложении Яндекса режимов так же нет. Однако HA не понимает такого и валится с ошибками при попытке отрендерить любую карточку, связанную с термостатом.
`2024-01-08 17:27:09.238 ERROR (MainThread) [homeassistant.components.homekit.type_thermostats] climate.battery: Received invalid HVAC mode: unknown`

Попытался обойти эту проблему через customize.yaml:
```
climate.battery:
  min_temp: 5
  max_temp: 35
  hvac_modes:
    - "off"
    - "heat"
```

Однако при установке "heat" появляется ошибка:
```
2024-01-08 17:26:59.560 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140394607210048] {'request_id': '5f0fda6c-5888-4e03-84de-3e092fd238d2', 'status': 'error', 'code': 'INTERNAL_ERROR', 'message': 'Случилось что-то непонятное. Подождите немного и попробуйте ещё раз.'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/yandex_station/climate.py", line 124, in async_set_hvac_mode
    await self.quasar.device_action(
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 353, in device_action
    assert resp["status"] == "ok", resp
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'request_id': '5f0fda6c-5888-4e03-84de-3e092fd238d2', 'status': 'error', 'code': 'INTERNAL_ERROR', 'message': 'Случилось что-то непонятное. Подождите немного и попробуйте ещё раз.'}
```

Что интересно - термостат таки включается.

Есть ли способ это как-то исправить?

**Comment by AlexxIT** [comment]
Нужно получить описание устройства (пример тут #366):
- в https://yandex.ru/quasar/ зайти в устройство
- в консоли браузера на закладке Network посмотреть как выглядит описание устройства https://yandex.ru/quasar/iot/device/xxx

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
