### ISSUE TITLE
Устройства недоступны после перезагрузки интеграции.

### ISSUE THREAD

**Issue by Hipokys** [AlexxIT/YandexStation#435]
После последнего релиза.
.Logger: homeassistant.config_entries
Source: config_entries.py:561
First occurred: 17:44:52 (1 occurrences)
Last logged: 17:44:52

Error unloading entry ***** for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 125, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by Opontios** [comment]
Откат на v3.13.0 решает проблему. Удалнеие и перенастройку интеграции еще не пробовал с последней версией.

**Comment by Opontios** [comment]
Переустановка интеграции с новой авторизацией не помогает. Только откат к прошлой версии. Только вот странно, это у нас двоих только?
