### ISSUE TITLE
Недостатки цветных яндекс лампочек и группы из них.

### ISSUE THREAD

**Issue by MikhailTeddy** [AlexxIT/YandexStation#445]
2 лампочки YNDX-00010 и YNDX-00019. В едином списке эффектов содержит цвета, как в УДЯ, а так же режимы (12 эффектов), внизу списка. Управление всё работает, кроме режимов. При выборе режима (внизу списка эффектов - алиса, вчеринка...),  -

 "Не удалось вызвать службу light/turn_on. 'scence'".
 
![лампочка](https://github.com/AlexxIT/YandexStation/assets/126555805/62bc8e8d-8a42-4b94-8101-4e4490188418)

В УДЯ Сделана группа из этих ламп. С новой интеграцией группа из ламп теперь успешно передаётся в HA. Карточка у группы
такая же как у лампочки, но управление полностью не рабочее. Например при включении:

"Не удалось вызвать службу light/turn_on. https://iot.quasar.yandex.ru/m/user/devices/........-....-....-....-............/actions return 404 status."
(точечки, это id)
При выборе режима, ошибка аналогичная  1 лампочки - Не удалось вызвать службу light/turn_on. 'scence'

HA получает состояние лампочек по отдельности и группы при управлении ими из УДЯ.
Получение параметров лампочек автоматическое ( в конфиге - имя группы - имя лампочки).

**Comment by MikhailTeddy** [comment]
Группу "освещение" можно сделать средствами HA, во вспомогательных объектах, и при желании передать этот объект в УДЯ через интеграцию Yandex Smart Home. Тогда группа будет работать как 1 лампочка. Но режимы не будут работать, всё с той же ошибкой.

**Comment by MikhailTeddy** [comment]
Не знаю как получить, запустил tail -f home-assistant.log, выбрал эффект. вот что вывалило:
             ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/light.py", line 123, in async_turn_on
    await self.quasar.device_actions(self.device["id"], **payload)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/core/yandex_quasar.py", line 444, in device_actions
    "devices.capabilities.custom.button" if k.isdecimal() else IOT_TYPES[k]
                                                               ~~~~~~~~~^^^

**Comment by MikhailTeddy** [comment]
Со стороны яндекс умного дома, интерфейс яндекс лампчки имеет "цвет"выбор цветов, и отдельно "Режимы" - выбор эффектов. Со стороны HA в интерфейсе выбор эффектов выдаёт в одном списке цвета, и в конце списка "режимы". Выбор цвета работает, а вот при выборе в конце списка любого из 12 "режима" выдаёт ошибку

**Comment by AlexxIT** [comment]
Похоже на огрызок лога. Может удасться получить полный текст ошибки?

**Comment by MikhailTeddy** [comment]
2024-02-17 14:05:05.013 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139932814475968] 'scene'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/light.py", line 123, in async_turn_on
    await self.quasar.device_actions(self.device["id"], **payload)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_station/core/yandex_quasar.py", line 444, in device_actions
    "devices.capabilities.custom.button" if k.isdecimal() else IOT_TYPES[k]
                                                               ~~~~~~~~~^^^
KeyError: 'scene'

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0
