### ISSUE TITLE
ConnectionResetError: Cannot write to closing transport

### ISSUE THREAD

**Issue by theodorx7** [AlexxIT/YandexStation#451]
**Component version**
v3.13.2

**HA core version**
2024.1.5

**Ошибка**
```
Logger: custom_components.yandex_station.core.yandex_glagol
Source: custom_components/yandex_station/core/yandex_glagol.py:101

Яндекс станция | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 101, in _connect
    async for msg in self.ws:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 312, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 280, in receive
    await self.pong(msg.data)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 160, in pong
    await self._writer.pong(message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 709, in pong
    await self._send_frame(message, WSMsgType.PONG)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 675, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by theodorx7** [comment]
Ошибка вроде больше не наблюдалась. При этом я уже использовал HA 2024.2.X и 2024.3.0.
