### ISSUE TITLE
Яндекс Станция Недоступно

### ISSUE THREAD

**Issue by itsyuni** [AlexxIT/YandexStation#453]
Привязан второй аккаунт с Станцией 1 поколения – но она не работает, пишет Недоступно

С Станцией Лайт все ок, а именно 1 поколения нет. 
<img width="607" alt="image" src="https://github.com/AlexxIT/YandexStation/assets/24845145/a47e599f-ef0e-4bbc-a24f-aa621fb1725d">

**Comment by Kyri270563** [comment]
Тоже стала Я.Станция Мини не доступна.
После переустановки интеграции вообще не находит станции.

**Comment by AlexxIT** [comment]
По скриншоту проблему врядли получится найти.

**Comment by Vinndimon** [comment]
@AlexxIT авторизован через купи (другие методы не работают вообще). Так же проблема что и у автора. При перезапуске в логах вылезает следующее:

**Comment by AlexxIT** [comment]
Удаление интеграции реализовано криво. Так что это нормальная ошибка. Частые добавления интеграции могут вызвать у Яндекса подозрение на взлом

**Comment by ipanzo** [comment]
такая же беда верся яндекса 3.12.2 Core 2024.2.2 Supervisor 2024.02.0 Operating System 11.5 все 3 колонки не доступны

**Comment by burabaika** [comment]
+1
в какой то момент станция стала недоступна
после удаления и 100 попыток войти всё таки вошел, но колонки нет

**Comment by Sr-psycho** [comment]
Такая же произошла проблема пару дней назад. Отвалились две миньки (теперь это устройство не поддерживается ....) . Удалял и добавлял. Но панель управления так и не появилась. В системе ничего не менялось

**Comment by Sr-psycho** [comment]
Такое вот  лог

```2024-09-19 08:49:51.667 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_quasar] Получение списка устройств.
2024-09-19 08:49:52.377 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_session] Обновление CSRF-токена, proxy: None
2024-09-19 08:49:52.778 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_session] Обновление CSRF-токена, proxy: None
2024-09-19 08:49:53.633 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 198, in load_speakers
    scenario = next(
               ^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/yandex_station/media_player.py", line 37, in async_setup_entry
    for speaker in await quasar.load_speakers():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 202, in load_speakers
    scenario = await self.add_scenario(device_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 284, in add_scenario
    assert resp["status"] == "ok", resp
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'request_id': '416008c7-2036-42de-adad-2760daf02a23', 'status': 'error', 'code': 'NAME_IS_ALREADY_TAKEN', 'message': 'Данное имя уже используется'}
```

**Comment by AlexxIT** [comment]
@Sr-psycho обычно такое бывает, когда настраивалась ещё какая-то интеграция с колонками. Например в Node-RED.

**Comment by nikolay1987123** [comment]
тоже все колонки пропали. что делать?

**Comment by ipanzo** [comment]
> тоже все колонки пропали. что делать?
Установи максимально старую версию

**Comment by ipanzo** [comment]
> тоже все колонки пропали. что делать?

Установи максимально старую версию
