### ISSUE TITLE
Не удалось загрузить эквалайзер

### ISSUE THREAD

**Issue by HGRT846** [AlexxIT/YandexStation#456]
Вот ошибка:

```
Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.yandex_station.select
Source: custom_components/yandex_station/select.py:106
Integration: Yandex.Station (documentation, issues)
First occurred: 16:34:02 (44 occurrences)
Last logged: 19:33:02

Не удалось загрузить эквалайзер
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('213.180.193.230', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/yandex_station/select.py", line 106, in async_update
    conf: dict = await self.quasar.get_device_config(self.device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 399, in get_device_config
    r = await self.session.get(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 467, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 500, in _request
    r = await getattr(self.session, method)(url, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host quasar.yandex.ru:443 ssl:default [Connect call failed ('213.180.193.230', 443)]

```

Она преследуеться двумя такими:

```
Logger: homeassistant.components.select
Source: helpers/entity_platform.py:858
Integration: Выбор (documentation, issues)
First occurred: 16:32:21 (164 occurrences)
Last logged: 19:32:51

Updating yandex_station select took longer than the scheduled update interval 0:00:30
```

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1186
First occurred: 16:32:01 (44 occurrences)
Last logged: 19:31:01

Update of select.yandex_station_ [ID ПЕРВОЙ СТАНЦИИ] _equalizer is taking over 10 seconds
Update of select.yandex_station_ [ID ВТОРОЙ СТАНЦИИ] _equalizer is taking over 10 seconds
```

Пробовал пинговать/подключаться с компютера, всё работают, пинговал напрямую с роутера - работает, подозреваю что ошибка либо в интеграции либо же home assistant блокирует подключение
![Untitefefefled](https://github.com/AlexxIT/YandexStation/assets/55946883/d2b7fe17-d25f-4217-b014-4c039aaa0fa9)

Я проживаю не на територии России, возможно проблемы могут быть из-за этого?

**Comment by HGRT846** [comment]
Я временно решил проблему, деактивировал эквалайзеры...

**Comment by AlexxIT** [comment]
`Cannot connect to host quasar.yandex.ru:443` - проблема с интернетом, интеграция ничего не может с этим сделать
