### ISSUE TITLE
Яндекс Мини2. Не удалось загрузить эквалайзер

### ISSUE THREAD

**Issue by garry0garry** [AlexxIT/YandexStation#464]
Часто вижу такую ошибку:
```

Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.yandex_station.select
Source: custom_components/yandex_station/select.py:106
Integration: Yandex.Station (documentation, issues)
First occurred: 07:11:12 (484 occurrences)
Last logged: 09:11:43

Не удалось загрузить эквалайзер
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/select.py", line 106, in async_update
    conf: dict = await self.quasar.get_device_config(self.device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 399, in get_device_config
    r = await self.session.get(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 467, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 516, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 516, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 518, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://quasar.yandex.ru/get_device_config return 403 status

```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0
