### ISSUE TITLE
Проблема с yandex_station - Attempt to decode JSON with unexpected

### ISSUE THREAD

**Issue by alxpanther** [AlexxIT/YandexStation#47]
Был в отпуске, стояла версия 2.2.0 и все отлично работало (Irbis A). Приехал, вижу изменилось API. Поставил последнюю 2.2.8 и не подключается. В логах такое:
```
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 82, in init
    speakers = await self.load_speakers()
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 208, in load_speakers
    resp = await r.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='https://iot.quasar.yandex.ru/m/user/devices
2020-08-10 10:08:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/yandex_station/__init__.py", line 151, in async_setup
    for speaker in speakers:
```
Причем руками при заходе на https://iot.quasar.yandex.ru/m/user/devices все отдается. JSON, хотя и не с первого символа идет, а пару пробелов в начале.

Правда, я пока был в отпуске, то меня на двухфакторную, но потом заметил, что с подключением тут гемор будет и вернул все обратно - колонку переподключил конечно с новым паролем и его же в конфиге прописал.

**Comment by AlexxIT** [comment]
В папке с конфигом надо удалить файл `.yandex_station.json`. Он скрытый. И перезагрузить ХА.

**Comment by alxpanther** [comment]
> В папке с конфигом надо удалить файл `.yandex_station.json`. Он скрытый. И перезагрузить ХА.
Да, спасибо. Все сработало.
