### ISSUE TITLE
ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/YandexStation#503]
ХА - 2024.5.0
Интеграция - 3.15.1
сыпет каждые 3 минуты по 7 ошибок, ровно по количеству станций в локальной сети

to reproduce follow https://github.com/home-assistant/core/issues/115071#issuecomment-2044330307

```
2024-05-03 09:09:20.843 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:20.844 WARNING (zeroconf-ServiceBrowser-_yandexio._tcp-127) [py.warnings] /usr/local/lib/python3.12/threading.py:1073: RuntimeWarning: coroutine '_init_local_discovery.<locals>.found_local_speaker' was never awaited
  self.run()
2024-05-03 09:09:21.584 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:21.584 WARNING (zeroconf-ServiceBrowser-_yandexio._tcp-127) [py.warnings] /usr/local/lib/python3.12/threading.py:1073: RuntimeWarning: coroutine '_init_local_discovery.<locals>.found_local_speaker' was never awaited
  self.run()
2024-05-03 09:09:21.586 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:22.037 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:22.377 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:23.001 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
2024-05-03 09:09:25.011 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-127) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 298, in _zeroconf_handler
    self.loop.create_task(coro)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
```

**Comment by to4ko** [comment]
а на втором инстансе (там ХА 2024.4.4) сразу **RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one**

```

2024-05-03 09:45:23.320 ERROR (zeroconf-ServiceBrowser-_yandexio._tcp-128) [asyncio] Unhandled error in exception handler
context: {'message': 'Task was destroyed but it is pending!', 'task': .found_local_speaker() running at /config/custom_components/yandex_station/__init__.py:198> created at /usr/local/lib/python3.12/asyncio/base_events.py:457>, 'source_traceback': [, , , ]}
handle_traceback: Handle created at (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 138, in _async_loop_exception_handler
    logger.error(
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 279, in emit
    self.hass.bus.fire(EVENT_SYSTEM_LOG, entry.to_dict())
  File "/usr/src/homeassistant/homeassistant/core.py", line 1378, in fire
    self._hass.loop.call_soon_threadsafe(
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1869, in call_exception_handler
    ctx.run(self._exception_handler, self, context)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 138, in _async_loop_exception_handler
    logger.error(
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1568, in error
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/config/custom_components/hass_diagnostics/sensor.py", line 85, in emit
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 690, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
