### ISSUE TITLE
Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by yundin2000** [AlexxIT/YandexStation#510]
Перестала работать интеграция, устройства, прокинутые в ХА стали недоступны

**Comment by yellow-sky** [comment]
Аналогично

**Comment by Scrubi19** [comment]
+

**Comment by AlexxIT** [comment]
Не могу подтвердить. Недостаточно информации для повторения проблемы.

**Comment by MaximAl065** [comment]
при попытке настроить интеграцию (только подключил) получил ту же ошибку.

**Comment by vtimer** [comment]
Таже история.
`2024-06-24 22:23:29.014 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from yandex_station, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'yandex_station' custom integration
2024-06-24 22:23:30.088 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/config_flow.py", line 73, in async_step_user
    description_placeholders={"qr_url": await self.yandex.get_qr()},
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by MikeSviblov** [comment]
Та же проблема при первичной установке

**Comment by Losenmann** [comment]
Аналогичная проблема

**Comment by AlexxIT** [comment]
"Перестала работать интеграция" и "первичная настройка" это совершенно разные вещи.
Проблемы при первичной настройки известны. Решаются повторными попытками через несколько часов.

А "перестала работать" в моём понимании это - интеграция работала и вдруг перестала (без вмешательства пользователя в настройки и тп).

**Comment by CRUSH-09** [comment]
Та же самая проблема. Ничего не трогал в интеграции, вчера еще работала. Сегодня с утра заметил, что ни одно устройство из Умного дома Яндекс, не присутствуют в НА. Зашел в интеграции, и вижу, что интеграция Яндекс Станция с ошибкой: не удалось настроить. При попытке входа в настройки, выходит сообщение, как в заголовке темы.

**Comment by grizzlylife** [comment]
Интеграция отваливается после обновления на 2024.8.0 и 2024.8.1. Если откатить версию продолжает работать.

В журнале HA вижу:
```
Регистратор: custom_components.yandex_station.core.yandex_session
Источник: custom_components/yandex_station/core/yandex_session.py:411


Login with token error: {'status': 'error', 'errors': ['oauth_token.invalid']}

```
Изменить настройки так же не могу пишет:
`Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble`

**Comment by AlexxIT** [comment]
Вряд-ли токен Яндекса как-то связан с минорным обновлением ХА.
Скорее всего были ручные изменения в авторизации Яндекса.
Случаев, когда токен сам по себе кончается, за эти несколько лет, я не встречал.

**Comment by fixid-pub** [comment]
Аналогично отвалилось после последней обновы HA, переустановка или перенастройка не помогают 
Вот лог:

```
Регистратор: aiohttp.server
Источник: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:428
Первое сообщение: 11:56:45 (1 сообщений)
Последнее сообщение: 11:56:45
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 459, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/config_flow.py", line 226, in async_step_init
    quasar: YandexQuasar = self.hass.data[DOMAIN][self.config_entry.unique_id]
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'yandex_username_bla_bla'
```

Походу яндекс что то поменял со своей стороны

**Comment by fixid-pub** [comment]
> Аналогично отвалилось после последней обновы HA, переустановка или перенастройка не помогают Вот лог:
> 
> ```
> Регистратор: aiohttp.server
> Источник: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:428
> Первое сообщение: 11:56:45 (1 сообщений)
> Последнее сообщение: 11:56:45
> Error handling request
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 459, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
>     resp = await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
>     result = await handler(request, **request.match_info)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
>     return await func(self, request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
>     return await super().post(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
>     return await method(view, request, data, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
>     return await self._post_impl(request, data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
>     result = await self._flow_mgr.async_init(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in async_init
>     result = await self._async_handle_step(flow, flow.init_step, data)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
>     result: _FlowResultT = await getattr(flow, method)(user_input)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/yandex_station/config_flow.py", line 226, in async_step_init
>     quasar: YandexQuasar = self.hass.data[DOMAIN][self.config_entry.unique_id]
>                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: 'yandex_username_bla_bla'
> ```
> 
> Походу яндекс что то поменял со своей стороны


Починилось достаточно банально.
"поломанную" интеграцию не удаляем, открываем Устройства и службы -> Добавить интеграцию -> yandex.station и авторизовываемся только по QR! При использовании других опцией в случае успешной авторизации ошибка сохранялась.

**Comment by toxig** [comment]
Аналогичная проблема после обновления на Yandex.Station 3.18.3
Повторная авторизация через QR валилась с ошибкой.

Вручную откатился на Yandex.Station [3.18.2](https://github.com/AlexxIT/YandexStation/releases/tag/v3.18.2), повторил авторизацию через QR - все заработало.

**Comment by AlexxIT** [comment]
Между этими двумя версиями и близко не менялся код работы с облаком. Просто совпадение.

**Comment by k0nstantin1** [comment]
> Аналогичная проблема после обновления на Яндекс.Станции 3.18.3 Повторная авторизация через QR валилась с ошибкой.
> 
> Вручную откатился на Яндекс.Станцию [​​3.18.2](https://github.com/AlexxIT/YandexStation/releases/tag/v3.18.2) , повторил авторизацию через QR - все заработало.

Все тоже самое.
Обновился сегодня на 3.18.3 (не запомнил с какой, но не обновлялся около месяца) и пропала авторизация
Интеграция выдавала ошибки:

Требуется внимание
Не удалось настроить:
Ошибка
Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble

Попытка авторизоваться через QR ни к чем не привела, при этом авторизация прошла без ошибки.
Откатил на 3.18.2 и даже повторная авторизация не потребовалась - заработало сразу.

**Comment by grizzlylife** [comment]
Я не уверен что это тоже самое, но у меня была очень похожая проблема 3 месяца назад, несколько раз отваливалась авторизация и не возможно было заново авторизоваться (не помню ошибку)..  Но помню, я удалил дополнение и поставил заново, после чего все взлетело, попробуйте, отпишитесь..

**Comment by incko84** [comment]
> Я не уверен что это тоже самое, но у меня была очень похожая проблема 3 месяца назад, несколько раз отваливалась авторизация и не возможно было заново авторизоваться (не помню ошибку).. Но помню, я удалил интеграцию и поставил заново, после чего все взлетело по QR коду, попробуйте, отпишитесь..

не пашет хоть тресни, я уже и на 18,2 откатывался толку нет.... Авторизация и по куару и по почте проходит но устройств нет и ошибка 500

**Comment by poisondima** [comment]
Тоже долго воевал с QR ничего не помогало, пока не поставил v3.18.4 и там сразу пошло, даже не нужно было что-то настраивать.

**Comment by AlexxIT** [comment]
"v3.18.4" ещё не существует. Но идея верная, нужно поставить последнюю бета-версию, чтоб авторизация (ошибка 500) прошла успешно.

**Comment by tobatya** [comment]
Подтверждаю есть проблема при установке версии 3.19 интеграция перестает работать вылетает с ошибкой 
Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble.
Откатился на версию 3.18.3  все заработало

**Comment by Volt220380** [comment]
не рабботает никак. Откатывался поэтапно и к варсии 3.18.3 и 3.18.1 ошибка 500 хоть ты тресни. Что делать? кто как победил помимо откатов к ранним версиям?

**Comment by Grawe89** [comment]
Думал что само пройдет, но не проходит.
Перебирал разные версии. Не помогло

[home-assistant_yandex_station_2025-07-10T21-48-15.313Z.log](https://github.com/user-attachments/files/21171687/home-assistant_yandex_station_2025-07-10T21-48-15.313Z.log)

**Comment by AlexxIT** [comment]
@Grawe89 удалите из Яндекса все сценарии, имя которых начинается на ХА

**Comment by Grawe89** [comment]
> [@Grawe89](https://github.com/Grawe89) удалите из Яндекса все сценарии, имя которых начинается на ХА

Помогло) 
Спасибо огромное!!

**Comment by Volt220380** [comment]
> [@Grawe89](https://github.com/Grawe89) удалите из Яндексы в обществе, имя которых навинетсья на Ха

Спасибо, проблема решена!

**Comment by AlexxIT** [comment]
Закрываю, поскольку так и не было подробностей изначальной проблемы.

https://github.com/AlexxIT/YandexStation/releases/tag/v3.21.0
