### ISSUE TITLE
Error during setup of component yandex_station

### ISSUE THREAD

**Issue by AlexeyHimki** [AlexxIT/YandexStation#52]
Добрый день!

Перестал работать компонент, при загрузке HA ошибки:

Logger: custom_components.yandex_station.yandex_quasar
Source: custom_components/yandex_station/yandex_quasar.py:208
Integration: yandex_station (documentation)
First occurred: 9:39:23 (1 occurrences)
Last logged: 9:39:23

Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 82, in init
    speakers = await self.load_speakers()
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 208, in load_speakers
    resp = await r.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://iot.quasar.yandex.ru/m/user/devices')

и

Logger: homeassistant.setup
Source: custom_components/yandex_station/__init__.py:151
First occurred: 9:39:23 (1 occurrences)
Last logged: 9:39:23

Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/yandex_station/__init__.py", line 151, in async_setup
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable

Yandex.Station 2.2.8
Home Assistant 0.114.3

**Comment by varakirill** [comment]
Такая же ошибка была - помогло удаление файла .yandex_station,json в корне папки config/

**Comment by AlexxIT** [comment]
Ага. Куки начали у пользователей протухать. Напишу фикс. А пока можно просто вручную удалить файл `.yandex_station.json` в папке конфига и перезапустить ХА

**Comment by interkom** [comment]
такая же ошибка. Удаление .yandex_station.json не помогает
Снёс и заново поставил компонент. Тоже не помогло.
Ошибки в логе.

Уровень: ERROR
Logger: homeassistant.setup
Source: custom_components/yandex_station/__init__.py:151
First occurred: 11:31:58 (1 occurrences)
Last logged: 11:31:58

Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/yandex_station/__init__.py", line 151, in async_setup
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable

и

Уровень: ERROR
Logger: custom_components.yandex_station.yandex_quasar
Source: custom_components/yandex_station/yandex_quasar.py:35
Integration: yandex_station (documentation)
First occurred: 11:31:58 (1 occurrences)
Last logged: 11:31:58

Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 94, in init
    scenarios = await self.load_scenarios()
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 272, in load_scenarios
    return {
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 273, in <dictcomp>
    decode(d['name']): d
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 35, in decode
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 35, in <listcomp>
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
ValueError: substring not found

Что ещё можно попробовать ?

**Comment by interkom** [comment]
как мне показалось, перестало это работать, когда я в configuration.yaml ошибочно прописал следующие строки

samsungtv:
  - host: 192.168.3.52
    name: LR-TV

media_player:
  - platform: samsungtv
    host: 192.168.3.52
    port: 8801
    mac: 8c:79:f5:61:5d:d7
    name: SamsungTV-Living_room

IP адрес указан одинаковый !

**Comment by AlexxIT** [comment]
@AlexeyHimki помогло?

**Comment by Alxspb** [comment]
При похожей проблеме удаление конфига помогло, authToken сгенерировался заново и плагин заработал.

**Comment by AlexxIT** [comment]
Исправлено в последних релизах
