### ISSUE TITLE
Не могу установить аддон

### ISSUE THREAD

**Issue by Yar1klamer** [AlexxIT/YandexStation#532]
```
Регистратор: homeassistant.components.websocket_api.http.connection
Источник: custom_components/hacs/repositories/base.py:698
интеграция: Home Assistant WebSocket API ([документация](https://www.home-assistant.io/integrations/websocket_api), [проблемы](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
Первое сообщение: 00:25:22 (1 сообщений)
Последнее сообщение: 00:25:22

[546705593664] Error handling message: Unknown error (unknown_error) Server from 192.168.1.5 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/base.py", line 977, in async_install_repository
    await self.download_content(version_to_install)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/base.py", line 628, in download_content
    await self.download_repository_zip()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/base.py", line 698, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)
  File "/usr/lib/python3.11/zipfile.py", line 1689, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.11/zipfile.py", line 1735, in _extract_member
    os.makedirs(upperdirs)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/custom_components/yandex_station'
```

Помогите пожалуйста,что делать?
Заранее спасибо

**Comment by AlexxIT** [comment]
Какие-то проблемы с настройкой linux, где вы всё это делаете. Не связано с этой интеграцией.
