### ISSUE TITLE
Одна колонка их двух перестала произносить текст

### ISSUE THREAD

**Issue by almirus** [AlexxIT/YandexStation#534]
ДД
Две колонки мини и лайт, 2 дня назад обе произносили тексты по сценариям из HA

![image](https://github.com/user-attachments/assets/0fb50d3c-f1ba-437d-8efb-d580299d2731)

Сейчас вызываю 
```
action: media_player.play_media
target:
  device_id:
    - bcfde19998697aa7e3fce7a1ba1dd816
    - 3888d5cf11e1e64f8e49297fec53934b
data:
  media_content_type: text
  media_content_id: тест test
```
произносит только Лайт, в логах про Мини колонку пусто

```
2024-08-20 08:50:37.706 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139944915495248] Error handling message: Unknown error (unknown_error) almirus from 192.168.0.63 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 514, in handle_manifest_list
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'tuya_ble' not found.
2024-08-20 08:50:46.200 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_quasar] Яндекс Лайт df3c => cloud | тест tert
2024-08-20 08:50:47.318 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_station] Яндекс Лайт df3c | yandex_speaker: {'instance': 'phrase_action', 'value': 'тест tert', 'entity_id': 'media_player.yandex_station_lr00000000000005445500008ae3df3c', 'name': 'Яндекс Лайт df3c'}

```

ЗЫ сама колонка в сети она и диалоги ведет и устройствами моего умного дома из HA через Yandex Smart Home управляет.

**Comment by almirus** [comment]
эм, догадался перезагрузить колонку, теперь все работает
