### ISSUE TITLE
Ошибка после обновления HACS до версии 2.0.0

### ISSUE THREAD

**Issue by KotsAO** [AlexxIT/YandexStation#536]
После обновления HACS до версии 2.0.0 возникла проблема. Выдаются такие ошибки (приведено для light, но аналогичные ошибки для cover, humidifier, climate):

```
Регистратор: homeassistant.components.light
Источник: helpers/entity_platform.py:364
интеграция: Освещение (документация, проблемы)
Первое сообщение: 09:26:34 (3 сообщений)
Последнее сообщение: 09:57:02

Error while setting up yandex_station platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/yandex_station/light.py", line 13, in async_setup_entry
    for quasar, device, config in hass_utils.incluce_devices(hass, entry)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.yandex_station.hass.hass_utils' has no attribute 'incluce_devices'
```

**Comment by AlexxIT** [comment]
Вероятно какой-то баг Hass. Нужно перескачать через него. Или перескачать с github вручную.
