### ISSUE TITLE
Exception: https://quasar.yandex.net/glagol/token return 429 status

### ISSUE THREAD

**Issue by ibuffy** [AlexxIT/YandexStation#543]
Добрый день! Возникла ошибка ;(

Регистратор: custom_components.yandex_station.core.yandex_glagol
Источник: custom_components/yandex_station/core/yandex_glagol.py:90
интеграция: Yandex.Station ([документация](https://github.com/AlexxIT/YandexStation), [проблемы](https://github.com/AlexxIT/YandexStation/issues))
Первое сообщение: 10:55:42 (30 сообщений)
Последнее сообщение: 12:04:32

Яндекс Станция Макс | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 90, in _connect
    self.device_token = await self.get_device_token()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 56, in get_device_token
    r = await self.session.get(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 467, in get
    return await self._request_glagol(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 540, in _request_glagol
    return await self._request_glagol(url, retry - 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 540, in _request_glagol
    return await self._request_glagol(url, retry - 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 542, in _request_glagol
    raise Exception(f"{url} return {r.status} status")
Exception: https://quasar.yandex.net/glagol/token return 429 status

**Comment by hirotasoshu** [comment]
Аналогично, отвалилось локальное управление колонкой

**Comment by AlexxIT** [comment]
Вероятно сбой на серверах Яндекса. Массовые жалобы на отвал локальных API. И через какое-то время всё само вернулось назад.
