### ISSUE TITLE
Detected blocking call

### ISSUE THREAD

**Issue by kasitoru** [AlexxIT/YandexStation#574]
**Yandex.Station:** 3.16.0
**Home Assistant:** 2024.11.2
**HACS:** 2.0.1

В логах ошибки:

```Регистратор: homeassistant.util.loop

Источник: util/loop.py:136
Первое сообщение: 15 ноября 2024 г. в 23:34:06 (2 сообщений)
Последнее сообщение: 15 ноября 2024 г. в 23:34:06

Detected blocking call to listdir with args (PosixPath('/usr/local/lib/python3.12/site-packages/hass_frontend/frontend_latest'),) inside the event loop by custom integration 'yandex_station' at custom_components/yandex_station/core/utils.py, line 282: for child in path.iterdir(): (offender: /usr/local/lib/python3.12/pathlib.py, line 1056: for name in os.listdir(self):), please create a bug report at https://github.com/AlexxIT/YandexStation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/runner.py", line 157, in setup_and_run_hass hass = await bootstrap.async_setup_hass(runtime_config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 326, in async_setup_hass await async_from_config_dict(config_dict, hass) is not None File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 494, in async_from_config_dict await _async_set_up_integrations(hass, config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 1052, in _async_set_up_integrations await async_setup_multi_components(hass, stage_2_domains, config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 785, in async_setup_multi_components domain: hass.async_create_task_internal( File "/usr/src/homeassistant/homeassistant/core.py", line 841, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component result = await task File "/config/custom_components/yandex_station/__init__.py", line 111, in async_setup utils.fix_recognition_lang( File "/config/custom_components/yandex_station/core/utils.py", line 282, in fix_recognition_lang for child in path.iterdir():

Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.12/site-packages/hass_frontend/frontend_latest/50027.YzO4qlJ3guc.js'), 'rb') inside the event loop by custom integration 'yandex_station' at custom_components/yandex_station/core/utils.py, line 287: with open(child, "rb") as f: (offender: /config/custom_components/yandex_station/core/utils.py, line 287: with open(child, "rb") as f:), please create a bug report at https://github.com/AlexxIT/YandexStation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/runner.py", line 157, in setup_and_run_hass hass = await bootstrap.async_setup_hass(runtime_config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 326, in async_setup_hass await async_from_config_dict(config_dict, hass) is not None File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 494, in async_from_config_dict await _async_set_up_integrations(hass, config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 1052, in _async_set_up_integrations await async_setup_multi_components(hass, stage_2_domains, config) File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 785, in async_setup_multi_components domain: hass.async_create_task_internal( File "/usr/src/homeassistant/homeassistant/core.py", line 841, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component result = await task File "/config/custom_components/yandex_station/__init__.py", line 111, in async_setup utils.fix_recognition_lang( File "/config/custom_components/yandex_station/core/utils.py", line 287, in fix_recognition_lang with open(child, "rb") as f:```

**Comment by AlexxIT** [comment]
Это опция `recognition_lang` из YAML. Она вообще работает на современных версиях ХА? Я её давно убрал из README, но из кода пока не выпилил.

**Comment by kasitoru** [comment]
Убрал из конфига и ошибка пропала, спасибо! Оно там было еще с древних времен)))

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.18.1
