### ISSUE TITLE
Не удалось загрузить будильники

### ISSUE THREAD

**Issue by UltrasSlim** [AlexxIT/YandexStation#580]
Добрый день!
После обновления решил попробовать использовать будильники в календаре Home assistant. После активации на колонках объектов calendar в логи стала падать ошибка 

> Не удалось загрузить будильники
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/calendar.py", line 55, in async_update
    alarms = await self.quasar.get_alarms(self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 622, in get_alarms
    r = await self.session.post(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 448, in post
    return await self.request("post", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 496, in request
    return await self.request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 496, in request
    return await self.request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 498, in request
    raise Exception(f"{url} return {r.status} status")
Exception: https://rpc.alice.yandex.ru/gproxy/get_alarms return 500 status

Мне что-то нужно еще поправить?

**Comment by UltrasSlim** [comment]
> Иногда это API действительно возвращает 500. Какие-то проблемы на стороне Яндекса. Нужно добавить несколько попыток.

Тогда ждем обновления)

**Comment by AlexxIT** [comment]
Чтоб оно было - нужно оставить issue

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.18.0
