### ISSUE TITLE
Имеется задержка при воспроизведении на другом источнике + прерывание воспроизведения в случайных позициях композиции на воспроизводимом устройстве

### ISSUE THREAD

**Issue by Tyson44-rus** [AlexxIT/YandexStation#593]
Имеется задержка в 5-6 секунд между самой Алисой и устройством, на которое передается трансляция музыки. Из-за этого треки полностью не проигрываются и караоке невозможно пользоваться. Колхозное решение нашёл, но хотелось бы нормальной реализации устранения этой задержки.
Так же бывает, что воспроизведение просто прерывается на непонятных позициях любой композиции, то примерно в середине, то где-то на 2/3 на **воспроизводимом устройстве**, приходится заново включать тот же трек или включать следующий. Причем прерывание интересное, провожу пример, музыка перестает играть на 1:32 и дальше начинается бесконечный цикл в виде прошедших 5-6 секунд до 1:37-1:38 и дальнейшее возвращение к 1:32. На самой Алисе трек спокойно продолжает играть...

Устройства: Яндекс Станция Мини Новая (2), ресивер Denon, HEOS

**Comment by AlexxIT** [comment]
С задержкой проблема не решаема #547
Про прерывание на воспроизводимом устройстве слышу впервые. Возможно проблемы интеграции этого самого устройства (ресивера).

**Comment by Tyson44-rus** [comment]
Насчёт задержи понял, не сильно мешает, не видеозапись всё-таки.
Проблема с остановкой музыки однозначно не из-за интеграции ресивера, другие потоки хорошо идут. Я заметил, что на определенных треках это происходит, ну или если перестать переключать треки, то все хуже и хуже становится, чуть ли не в начале останавливается воспроизведение.
Так и не понял, в чем точно причина. Такое ощущение, что поток просто обрывается, а заново он, конечно, не запускается, приходится включать следующую песню.
Ещё заметил, что на каких-то песнях время воспроизведения от балды просто, чуть ли не полчаса показывает ресивер.

**Comment by AlexxIT** [comment]
А других плееров в ХА нет для теста?

**Comment by KirillShzzzzzz** [comment]
Подтверждаю, проблема с остановкой музыки постоянна и рандомна при трансляции на ресиверы Denon и Marantz

**Comment by AlexxIT** [comment]
Нужно проверять на версии v3.18.1

**Comment by KirillShzzzzzz** [comment]
> Нужно проверять на версии v3.18.1

Вчера на ней попробовал. Предварительно направил поток через Music Assistant (до этого через DLNA и HAOS).
При первом включении просто тишина до конца первой композиции, потом вроде все играет (долго проверять не смог, но на протяжении минут 15 все было ОК - раньше за это время уже проявлялись тормоза)
При остановке, а затем включении, ресивер начинает проигрывать старый поток (на котором остановили), а колонка новый. Останавливаешь, запускаешь заново - ОК.
Раньше на DLNA ресивер отображал на экране название композиции, теперь везде пишет Home Assistant (не критично)

**Comment by KirillShzzzzzz** [comment]
Проверил на Denon и Marantz - тормозов нет.
Из "неприятностей" - после постановки Алисы на паузу (стоп у нее нет) на ресивере остается висящий на паузе поток, который активируется при дальнейших манипуляциях с ним (если есть возможность при трансляции при остановке проигрывания Алисой останавливать и поток - было бы здорово); при установке источника (например после перезагрузки HA я это делаю автоматизацией) происходит включение ресивера и тут же начинает проигрываться висящий на паузе поток :)

**Comment by Den-88** [comment]
v3.18.3 
Тоже периодически прерывается трансляция на хромкаст.
Ловлю такую ошибку логах:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pychromecast/socket_client.py", line 548, in run
    if self._run_once() == 1:
       ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pychromecast/socket_client.py", line 599, in _run_once
    message = self._read_message()
  File "/usr/local/lib/python3.13/site-packages/pychromecast/socket_client.py", line 836, in _read_message
    payload_info = self._read_bytes_from_socket(4)
  File "/usr/local/lib/python3.13/site-packages/pychromecast/socket_client.py", line 818, in _read_bytes_from_socket
    chunk = self.socket.recv(min(msglen - bytes_recd, 2048))
  File "/usr/local/lib/python3.13/ssl.py", line 1285, in recv
    return self.read(buflen)
           ~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 1140, in read
    return self._sslobj.read(len)
           ~~~~~~~~~~~~~~~~~^^^^^
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] ssl/tls alert bad record mac (_ssl.c:2638)
```

**Comment by AlexxIT** [comment]
Вообще не касается этой интеграции. Вопросы к интеграции Хромкастов

**Comment by Den-88** [comment]
> Вообще не касается этой интеграции. Вопросы к интеграции Хромкастов

Согласен, но ошибка возникает только с этой интеграцией. 
Если транслировать например в music assistant, а с него уже на хромкаст, то всё работает стабильно...

**Comment by f1egmatik** [comment]
Слушаю яндекс-музыку на беспроводных колонках denon home, подключённых интеграцией heos. При плохом интернете (провайдер или ркн шалят), плохом вайфае (переключаю узлы домашней mesh-сети) колонки часто затыкаются. Причём, если две идентичные колонки объединены в стереопару (в приложении heos), то могут обе заглохнуть, может отдельно левая, может отдельно правая. Затыкаются, пока не придёт пора играть следующую песню. Так что я решил для себя, что это глюк самих колонок denon, которые требовательны к бесперебойности потока и не восстанавливают соединение с сервером яндекса.

**Comment by AlexxIT** [comment]
Трансляция идёт через ХА. К серверам Яндекса подключается ХА, колонки получают поток сервера ХА.
