### ISSUE TITLE
Ошибки при перезагрузке HA

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/YandexStation#62]
```
home-assistant    | Error doing job: Task exception was never retrieved
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/yandex_station/yandex_glagol.py", line 74, in _connect
home-assistant    |     await self.refresh_device_token(session)
home-assistant    |   File "/config/custom_components/yandex_station/yandex_glagol.py", line 48, in refresh_device_token
home-assistant    |     r = await session.get(
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 357, in _request
home-assistant    |     raise RuntimeError('Session is closed')
home-assistant    | RuntimeError: Session is closed
```

**Comment by fantomnotabene** [comment]
Не уверен, сюда же или не совсем, но
```
Logger: root
Source: custom_components/yandex_station/yandex_glagol.py:222 
First occurred: 2:36:07 (1 occurrences) 
Last logged: 2:36:07

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1721, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1479, in fire
    h(**kwargs)
  File "/config/custom_components/yandex_station/yandex_glagol.py", line 222, in _zeroconf_handler
    'host': str(ipaddress.ip_address(info.addresses[0])),
IndexError: list index out of range
```
