### ISSUE TITLE
Вопрос:  Смена пароля на яндексе

### ISSUE THREAD

**Issue by OXOTHuK1976** [AlexxIT/YandexStation#64]
Поменял пароль на яндекс, Yandex Station не может теперь авторизоваться 

2020-10-13 23:04:37 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\yandex_station\yandex_quasar.py", line 90, in init
    await self.login(self.main_token['access_token'])
  File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\yandex_station\yandex_quasar.py", line 219, in login
    assert resp['status'] == 'ok', resp
AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
2020-10-13 23:04:37 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):

Я так понимаю дело в куки или кэше токена, как можно почистить?

**Comment by AlexxIT** [comment]
Нужно удалить файл `.yandex_station.json` в папке конфига
