### ISSUE TITLE
Ошибка авторизации по логину-паролю: запрос капчи 

### ISSUE THREAD

**Issue by anklimov** [AlexxIT/YandexStation#66]
После удаления токена не может авторизоваться: 

2020-10-18 03:52:50 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 87, in init
    self.main_token = await self.get_main_token(username, password)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 177, in get_main_token
    assert 'x_token' in resp, resp
AssertionError: {'status': 'error', 'errors': ['captcha.required'], 'captcha_image_url': 'https://ext.captcha.yandex.net/image?key=00ABO9gL2U3I5feIbnaJ0ls8jWPXju44'}
2020-10-18 03:52:50 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yandex_station/__init__.py", line 78, in async_setup
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable

**Comment by anklimov** [comment]
Нашел аналогичный Issue
