### ISSUE TITLE
HA не подключается к аккаунты со следующей ошибкой

### ISSUE THREAD

**Issue by maximilianoloco** [AlexxIT/YandexStation#71]
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 117, in init_local
    self.local_token = await self.get_local_token(x_token)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 388, in get_local_token
    r = await self.session.post('https://oauth.mobile.yandex.net/1/token',
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError

**Comment by fr00kt** [comment]
А у меня после смены пароля аккаунта Яндекс вот с такой ошибкой
ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
File "/config/custom_components/yandex_station/yandex_quasar.py", line 90, in init
await self.login(self.main_token['access_token'])
File "/config/custom_components/yandex_station/yandex_quasar.py", line 219, in login
assert resp['status'] == 'ok', resp
AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
2020-11-02 01:22:42 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/yandex_station/__init__.py", line 158, in async_setup
for speaker in speakers:
TypeError: 'NoneType' object is not iterable

**Comment by AlexxIT** [comment]
@fr00kt удалить файл `.yandex_station.json` в папке конфига и перезагрузиться

@maximilianoloco возможно проблемы с Интернетом. Сложно сказать

**Comment by RakotVT** [comment]
Тоже есть проблема с авторизацией, но по одноразовому паролю, по логам авторизация вызывается до истечения срока жизни пароля
2020-11-02 12:35:17 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "/home/rakot/.homeassistant/custom_components/yandex_station/yandex_quasar.py", line 87, in init
    self.main_token = await self.get_main_token(username, password)
  File "/home/rakot/.homeassistant/custom_components/yandex_station/yandex_quasar.py", line 177, in get_main_token
    assert 'x_token' in resp, resp
В ответе 'errors': ['password.not_matched']

**Comment by fr00kt** [comment]
> @fr00kt удалить файл `.yandex_station.json` в папке конфига и перезагрузиться

Помогло

**Comment by AlexxIT** [comment]
@RakotVT значит ошибка гарантированно в пароле

**Comment by RakotVT** [comment]
> 
> 
> @RakotVT значит ошибка гарантированно в пароле

Прошу прощения, меня ввело в заблуждение дикое приложение Я.Ключ, которое в ответ на неверный пинкод генерило неверные пароли вместо того чтобы сказать что пинкод не тот
