### ISSUE TITLE
Ошибка oauth_token.invalid 

### ISSUE THREAD

**Issue by VadimOmsk** [AlexxIT/YandexStation#82]
Здравствуйте. 
Помогите плз. Вот такое начал выдавать сегодня HA в home-assistant.log.
Один раз в самом начале. Естественно колонки (irbis) не видит.
Сама колонка прекрасно работает (свет отопители и тд включает через компоненту Yandex Smart Home). Отвязывал привязывал колонку не помогло.
версия 2.3.1 с HACS
```
2020-11-26 19:00:13 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 90, in init
    await self.login(self.main_token['access_token'])
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 219, in login
    assert resp['status'] == 'ok', resp
AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
2020-11-26 19:00:13 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yandex_station/__init__.py", line 158, in async_setup
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable
```
config простейший 
```
yandex_station:
  username: username@yandex.ru
  password: passwordyandexmail

```

**Comment by VadimOmsk** [comment]
решено удалением /config/.yandex_station.json
