### ISSUE TITLE
Не устанавливается компонент на 118.4

### ISSUE THREAD

**Issue by torquemada163** [AlexxIT/YandexStation#84]
Так как на 118.4 не удается установить HACS, то установил компонент путем копирования папку `custom_components` паки с самим компонентом - `yandex_station`

В конфигурационный файл написал:
```
yandex_station:
  username: пользователь
  password: "пароль"
```

Пробовал писать и короткое имя, и длинное, с @yandex.ru
Двухфактороной авторизации нет. Пароль пробовал писать как в кавычках, так и без. Также пробовал OAuth токен. Всегда одна и та же ошибка:
```
2020-11-30 12:50:00 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
File "/config/custom_components/yandex_station/yandex_quasar.py", line 90, in init
await self.login(self.main_token['access_token'])
File "/config/custom_components/yandex_station/yandex_quasar.py", line 219, in login
assert resp['status'] == 'ok', resp
AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
2020-11-30 12:50:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/yandex_station/__init__.py", line 158, in async_setup
for speaker in speakers:
TypeError: 'NoneType' object is not iterable
```

Это та же проблема с асинхронной работой, что была сломана в 118.4?

**Comment by torquemada163** [comment]
Помогло закрепленное issue
https://github.com/AlexxIT/YandexStation/issues/52
