### ISSUE TITLE
Яндекс станция не подключается

### ISSUE THREAD

**Issue by danilovvs** [AlexxIT/YandexStation#98]
Станции мини работают нормально, а станция выдает ошибку

YandexStation (ERROR) - первое сообщение получено 5:46:25 и повторялось 3570 раз

```
Алиса в гостиной | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_glagol.py", line 121, in _connect
    await self.update(data)
  File "/config/custom_components/yandex_station/media_player.py", line 375, in update
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/yandex_station/media_player.py", line 255, in state_attributes
    attrs = super().state_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 841, in state_attributes
    value = getattr(self, attr)
  File "/config/custom_components/yandex_station/media_player.py", line 540, in source
    return SOURCE_HDMI if self.device_config.get('hdmiAudio') \
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by AlexxIT** [comment]
Должно быть поправлено в последнем релизе
